IF
	GlobalGT("AC#BeldasDies","GLOBAL",1)
THEN
	RESPONSE #100
	   DestroySelf()
END

IF
	Global("GoblinTrap","ACIL0A",20)
THEN
	RESPONSE #100
	   EscapeArea()
END

IF
	Global("GoblinTrap","ACIL0A",19)
	Global("GoblinAttack","LOCALS",0)
THEN
	RESPONSE #100
	   SetGlobal("GoblinAttack","LOCALS",1)
	   Enemy()
	   EquipRanged()
	   AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
	Global("GoblinTrap","ACIL0A",15)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
	Global("GoblinTrap","ACIL0A",15)
	!Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #50
	   Swing()
	RESPONSE #50
	 	Recoil()
	RESPONSE #50
		NoAction()	 
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

