IF
    Global("GithFight","ACIL28",2)
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        Enemy()
END

IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        Shout(89)
        Enemy()
END

IF
    See(NearestEnemyOf(Myself))
    Global("prepspells","LOCALS",0)
    !StateCheck(Myself,STATE_HASTED)
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("BD_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
        ReallyForceSpell(Myself,WIZARD_HASTE)  // SPWI305.SPL (Hast)
        SetGlobal("prepspells","LOCALS",1)
END

IF
    OR(5)
        See(NearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
    !GlobalTimerNotExpired("BD_Cast","LOCALS")
    !GlobalTimerNotExpired("Psi","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("Psi","LOCALS",THREE_ROUNDS)
        ForceSpell(LastSeenBy(Myself),PSIONIC_MIND_BLAST)  // SPIN775.SPL (Psi-Schlag)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_HORROR)  // SPWI205.SPL (Schrecken)
    !GlobalTimerNotExpired("BD_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
        Spell(NearestEnemyOf(Myself),WIZARD_HORROR)  // SPWI205.SPL (Schrecken)
END

IF
    OR(5)
        See(NearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melfs Säurepfeil)
    !GlobalTimerNotExpired("BD_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melfs Säurepfeil)
END

IF
    See(NearestEnemyOfType([0.0.0.FIGHTER_ALL]))
    !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    HaveSpell(WIZARD_CHARM_PERSON)  // SPWI104.SPL (Personen bezaubern)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_CHARM_PERSON)  // SPWI104.SPL (Personen bezaubern)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Farbkugel)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Farbkugel)
END

IF
    See(NearestEnemyOf(Myself))
    HPPercentLT(Myself,20)
    HasItemSlot(Myself,SLOT_MISC1)
THEN
    RESPONSE #100
        DisplayStringHead(Myself,46150)  // trinkt einen Trank
        UseItemSlot(Myself,SLOT_MISC1)
END

IF
    See(NearestEnemyOf(Myself))
    !StateCheck(Myself,STATE_INVISIBLE)
    !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
    HasItemSlot(Myself,SLOT_MISC0)
    Delay(6)
THEN
    RESPONSE #100
        DisplayStringHead(Myself,46150)  // trinkt einen Trank
        UseItemSlot(Myself,SLOT_MISC0)
END

IF
    See(NearestEnemyOf(Myself))
    HasItemSlot(Myself,SLOT_MISC2)
    Delay(12)
THEN
    RESPONSE #100
        DisplayStringHead(Myself,46150)  // trinkt einen Trank
        UseItemSlot(Myself,SLOT_MISC2)
END

IF
    See(NearestEnemyOf(Myself))
    HasItemSlot(Myself,SLOT_MISC3)
THEN
    RESPONSE #100
        UseItemSlot(Myself,SLOT_MISC3)
END

IF
    See(NearestEnemyOf(Myself))
    HasItemSlot(Myself,SLOT_MISC4)
    Delay(12)
THEN
    RESPONSE #100
        UseItemSlot(Myself,SLOT_MISC4)
END

IF
    See(NearestEnemyOf(Myself))
    HasItemSlot(Myself,SLOT_MISC5)
THEN
    RESPONSE #100
        UseItemSlot(LastSeenBy(Myself),SLOT_MISC5)
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),6)
END

