IF
    Range([PC],12)
    NumberOfTimesTalkedTo(0)
    See([PC])
THEN
    RESPONSE #100
        StartDialogueNoSet([PC])
END

IF
    See([PC])
    Dead("AC#DROW6")  // Zilna
    Global("AC#25KilledLolthPriestess","ACIL24",0)
THEN
    RESPONSE #100
        StartDialogueNoSet([PC])
END

IF
    See([PC])
    !Dead("AC#DROW6")  // Zilna
    Global("AC#25PactLolthPriestess","GLOBAL",2)
THEN
    RESPONSE #100
        StartDialogueNoSet([PC])
END

IF
    OR(3)
        AttackedBy([GOODCUTOFF],DEFAULT)
        Allegiance("AC#24DR1",ENEMY)  // Drow-Krieger
        Allegiance("AC#24MDF",ENEMY)  // Qall
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        SetGlobal("Drowfight","ACIL24",1)
        SetGlobal("AC#25_LolthPriestess","GLOBAL",10)
        Enemy()
END

IF
    Allegiance(Myself,ENEMY)
    OR(2)
        See(NearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
    Global("Summon_Mastiff","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Summon_Mastiff","LOCALS",1)
        CreateCreatureObject("AC#ILSM2",LastSeenBy(Myself),0,0,0)  // Schattenmastiff
END

IF
    Allegiance(Myself,ENEMY)
    OR(3)
        See(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
    Global("Summon_Mastiff","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Summon_Mastiff","LOCALS",1)
        CreateCreatureObject("AC#ILSM2",LastSeenBy(Myself),0,0,0)  // Schattenmastiff
END

IF
    See(NearestEnemyOf(Myself))
    Global("Summon_Mastiff","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Summon_Mastiff","LOCALS",1)
        CreateCreatureObject("AC#ILSM2",LastSeenBy(Myself),0,0,0)  // Schattenmastiff
END

IF
    See(NearestEnemyOf(Myself))
    HPPercentLT(Myself,50)
    Global("Gaerscloak","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Gaerscloak","LOCALS",1)
        ReallyForceSpellRES("AC#24GC",Myself)  // Gaers Mantel
END

IF
    LevelGT(Player1,14)
    See(NearestEnemyOf(Myself))
    Global("Gate","LOCALS",0)
    HaveSpellRES("AC#GATM")  // Tor
THEN
    RESPONSE #100
        SetGlobal("Gate","LOCALS",1)
        ForceSpellRES("AC#GATM",Myself)  // Tor
END

IF
    OR(2)
        LevelGT(Player1,12)
        Difficulty(HARDEST)
    See(NearestEnemyOf(Myself))
    HPPercentLT(Myself,30)
    Global("Gate","LOCALS",0)
    HaveSpellRES("AC#GATM")  // Tor
THEN
    RESPONSE #100
        SpellRES("AC#GATM",Myself)  // Tor
        SetGlobal("Gate","LOCALS",1)
END

IF
    HitBy([ANYONE],MISSILE)
    HaveSpell(CLERIC_PHYSICAL_MIRROR)  // SPPR613.SPL (Materiespiegel)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,CLERIC_PHYSICAL_MIRROR)  // SPPR613.SPL (Materiespiegel)
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_CHANT)  // SPPR203.SPL (Gesang)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Gesang)
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
    See("AC#24DR1")  // Drow-Krieger
    HaveSpell(CLERIC_STRENGTH_OF_ONE)  // SPPR312.SPL (Vereinte Stärke)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,CLERIC_STRENGTH_OF_ONE)  // SPPR312.SPL (Vereinte Stärke)
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Mantel der Furcht)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Mantel der Furcht)
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
    See("AC#24DR1")  // Drow-Krieger
    HPPercentLT("AC#24DR1",80)  // Drow-Krieger
    HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Massenheilung)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,CLERIC_MASS_CURE)  // SPPR514.SPL (Massenheilung)
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flammenschlag)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(NearestEnemyOf(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flammenschlag)
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Geistige Beherrschung)
    !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    !HasBounceEffects(LastSeenBy(Myself))
    HPGT(LastSeenBy(Myself),20)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(NearestEnemyOf(Myself),CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Geistige Beherrschung)
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(NearestEnemyOf(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
        SetInterrupt(TRUE)
END

IF
    Alignment(LastSeenBy(Myself),MASK_GOOD)
    HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unheiliges Verderben)
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unheiliges Verderben)
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

