IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        FadeToColor([30.0],0)
        ActionOverride("AC#7TTIA",DestroySelf())
        Wait(2)
        LeaveAreaLUAPanic("ACIL62","",[2740.467],SW)
        LeaveAreaLUA("ACIL62","",[2740.467],SW)
        MultiPlayerSync()
        MoveViewPoint([2740.467],INSTANT)
        SmallWait(5)
        FadeFromColor([30.0],0)
        EndCutSceneMode()
END

