IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        SetGlobal("AC#_CUTSCENE_BREAKABLE","GLOBAL",1)
        SetCutSceneBreakable(TRUE)
        FadeToColor([30.0],0)
        Wait(1)
        Wait(1)
        LeaveAreaLUAPanic("ACILD2","",[0.0],S)
        LeaveAreaLUA("ACILD2","",[0.0],N)
        MultiPlayerSync()
        MoveViewPoint([374.1333],INSTANT)
        Explore()
        SmallWait(5)
        FadeFromColor([40.0],0)
        ActionOverride("AC#DREA1",MoveToPoint([1543.379]))
        Wait(5)
        MoveViewPoint([1543.379],5)
        Wait(10)
        Wait(3)
        SetCutSceneBreakable(FALSE)
        SetGlobal("AC#_CUTSCENE_BREAKABLE","GLOBAL",0)
        ActionOverride("AC#DREA2",StartDialogueNoSet(Player1))
END

