IF
    True()
THEN
    RESPONSE #100
        CutSceneId("AC#28DRS")  // Drow-Magier-Sklave
        SetGlobal("AC#IL_KilledElderBrain","GLOBAL",1)
        ForceSpell("AC#IL28G",WIZARD_FIREBALL)  // Untotes Ältestenhirn
        Kill("AC#IL28G")  // Untotes Ältestenhirn
        CreateVisualEffect("AC#IL54B",[2196.1589])
        ScreenShake([20.20],5)
        OpenDoor("DOOR07")
        AmbientActivate("Smoke_wood",TRUE)
        Wait(3)
        ActionOverride("AC#ULIT2",StartDialogueNoSet([PC]))
END

