IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        ActionOverride("AC#DREA8",MoveToPoint([372.607]))
        ActionOverride("AC#DREA9",MoveToPoint([2080.1600]))
        FadeToColor([50.0],0)
        Wait(3)
        RestorePartyLocations()
        MultiPlayerSync()
        FadeFromColor([30.0],0)
        EndCutSceneMode()
        StartMovie("AC#23MVE")
        RestParty()
        SetGlobal("AC#ACIL23DreamReflection","GLOBAL",1)
        SetGlobal("AC#IL_BrainVision","GLOBAL",1)
END

