/*
AC#29MI4

Spiegelfalle AC#29MI4 in der Betrachterhöhle
*/
IF
	Entered([0.0.0.0.0.SUMMONED])
	!Dead("AC#BEH07")
	!StateCheck(LastTrigger,STATE_INVISIBLE)
	!StateCheck(LastTrigger,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
                IncrementGlobal("Trigger_AC#29MI4","ACIL29",1)
                ActionOverride("AC#BEH07",ReallyForceSpell("AC#29MI4",WIZARD_DEATH_SPELL))
                SmallWait(20)
		ReallyForceSpell(LastTrigger,WIZARD_DEATH_SPELL)
END

IF
	Entered([PC])
	!Dead("AC#BEH07")
	!StateCheck(LastTrigger,STATE_INVISIBLE)
	!StateCheck(LastTrigger,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
                IncrementGlobal("Trigger_AC#29MI4","ACIL29",1)
                ActionOverride("AC#BEH07",ForceSpell("AC#29MI4",BEHOLDER_FEAR))
                SmallWait(20)
		ForceSpell(LastTrigger,BEHOLDER_FEAR)
END


