IF
    NumberOfTimesTalkedTo(0)
    See([PC])
THEN
    RESPONSE #100
        StartDialogueNoSet([PC])
END

IF
    GlobalGT("AC#Ruvan_Treason","GLOBAL",0)
THEN
    RESPONSE #100
        DestroySelf()
END

IF
    Global("AC#IL27_DismissDwarves","GLOBAL",1)
THEN
    RESPONSE #100
        EscapeArea()
END

IF
    Global("AC#IL27_AidDwarves","GLOBAL",1)
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        ChangeEnemyAlly(Myself,GOODBUTBLUE)
        SetGlobal("AC#IL27_AidDwarves","GLOBAL",2)
END

IF
    See([ENEMY])
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),12)
END

IF
    Global("AC#IL27_AidDwarves","GLOBAL",2)
    !See([ENEMY])
    !Range(Player1,12)
    Delay(6)
THEN
    RESPONSE #100
        MoveToObject(Player1)
END

