IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        FadeToColor([30.0],0)
        ActionOverride("AC#2TTIA",DestroySelf())
        ActionOverride("ac#mal2t",EscapeAreaDestroy(0))
        Wait(2)
        LeaveAreaLUAPanic("ACIL50","",[3268.1910],S)
        LeaveAreaLUA("ACIL50","",[3268.1910],NE)
        MultiPlayerSync()
        MoveViewPoint([3268.1910],INSTANT)
        SmallWait(5)
        FadeFromColor([30.0],0)
        EndCutSceneMode()
END

