/*
AC#29MI2

Spiegelfalle AC#29MI2 in der Betrachterhöhle
*/
IF
	Entered([0.0.0.0.0.SUMMONED])
	!Dead("AC#BEH05")
	!StateCheck(LastTrigger,STATE_INVISIBLE)
	!StateCheck(LastTrigger,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
                IncrementGlobal("Trigger_AC#29MI2","ACIL29",1)
                ActionOverride("AC#BEH05",ReallyForceSpell("AC#29MI2",WIZARD_DEATH_SPELL))
                SmallWait(20)
		ReallyForceSpell(LastTrigger,WIZARD_DEATH_SPELL)
END

IF
	Entered([PC])
	!Dead("AC#BEH05")
	!StateCheck(LastTrigger,STATE_INVISIBLE)
	!StateCheck(LastTrigger,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
                IncrementGlobal("Trigger_AC#29MI2","ACIL29",1)
                ActionOverride("AC#BEH05",ForceSpell("AC#29MI2",BEHOLDER_FLESH_TO_STONE))
                SmallWait(20)
		ForceSpell(LastTrigger,BEHOLDER_FLESH_TO_STONE)
END


