IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        FadeToColor([30.0],0)
        Wait(1)
        Wait(1)
        LeaveAreaLUAPanic("ACILD1","",[0.0],S)
        LeaveAreaLUA("ACILD1","",[0.0],N)
        MultiPlayerSync()
        MoveViewPoint([2080.1600],INSTANT)
        Explore()
        SmallWait(5)
        FadeFromColor([40.0],0)
        ActionOverride("AC#DREA8",MoveToPoint([1066.1059]))
        ActionOverride("AC#DREA9",MoveToPoint([1003.1133]))
        MoveViewPoint([1066.1059],5)
        Wait(10)
        Wait(3)
        ActionOverride("AC#DREA8",StartDialogueNoSet(Player1))
END

