IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        MultiPlayerSync()
        Explore()
        SmallWait(5)
        SetGlobal("AC#_CUTSCENE_BREAKABLE","GLOBAL",1)
        SetCutSceneBreakable(TRUE)
        ActionOverride("AC#DREA8",MoveToPoint([609.811]))
        MoveViewPoint([609.811],5)
        Wait(5)
        SetCutSceneBreakable(FALSE)
        SetGlobal("AC#_CUTSCENE_BREAKABLE","GLOBAL",0)
        ActionOverride("AC#DREA8",Face(SEE))
        ActionOverride("AC#DREA8",StartDialogueNoSet(Player1))
END

