IF
    NumberOfTimesTalkedTo(0)
    Detect([PC])
THEN
    RESPONSE #100
        StartDialogueNoSet(LastSeenBy(Myself))
END

IF
    See(NearestEnemyOf(Myself))
    Global("GazeAttack","LOCALS",0)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #50
        SetGlobalTimer("WailingTimer","GLOBAL",THREE_ROUNDS)
        SetGlobal("GazeAttack","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    Global("GazeAttack","LOCALS",1)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #50
        ReallyForceSpellRES("AC#2DB1",NearestEnemyOf(Myself))  // Fluch des Berserkers
        SetGlobal("GazeAttack","LOCALS",2)
END

IF
    See(SecondNearestEnemyOf(Myself))
    !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    Global("GazeAttack","LOCALS",1)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #50
        ReallyForceSpellRES("AC#2DB1",SecondNearestEnemyOf(Myself))  // Fluch des Berserkers
        SetGlobal("GazeAttack","LOCALS",2)
END

IF
    See(NearestEnemyOf(Myself))
    Global("WailAttack","LOCALS",0)
    GlobalTimerExpired("WailingTimer","GLOBAL")
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        ReallyForceSpellRES("AC#2DB2",NearestEnemyOf(Myself))  // Verfluchter Schlachtruf
        SetGlobal("WailAttack","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("Wailbanshee","LOCALS",0)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        ForceSpellRES("AC#2DDB",NearestEnemyOf(Myself))  // Schrei der Todesfee
        SetGlobal("Wailbanshee","LOCALS",1)
END

IF
    !GlobalTimerNotExpired("TrueSeeing","LOCALS")
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    Detect(NearestEnemyOf(Myself))
    OR(12)
        StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
        StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
        StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
        StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
        StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
        StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
        StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
        StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
        StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
        StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
        StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
        StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("TrueSeeing","LOCALS",ONE_TURN)
        SpellNoDec(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (Wahrer Blick)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger des Todes)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(NearestEnemyOf(Myself),CLERIC_FINGER_OF_DEATH)  // SPPR708.SPL (Finger des Todes)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(NPC_BLADE_BARRIER)  // SPPR698.SPL (Klingenbarierre)
    RandomNum(2,1)
    Global("BladeBarrier","LOCALS",0)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,NPC_BLADE_BARRIER)  // SPPR698.SPL (Klingenbarierre)
        SetGlobal("BladeBarrier","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    HitBy([ANYONE],CRUSHING)
    HaveSpell(CLERIC_IRONSKIN)  // SPPR506.SPL (Eisenhaut)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,CLERIC_IRONSKIN)  // SPPR506.SPL (Eisenhaut)
END

IF
    See(NearestEnemyOf(Myself))
    RandomNum(2,1)
    HaveSpell(CLERIC_CONFUSION)  // SPPR709.SPL (Verwirrung)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,CLERIC_CONFUSION)  // SPPR709.SPL (Verwirrung)
END

IF
    See(NearestEnemyOf(Myself))
    RandomNum(2,2)
    HaveSpell(CLERIC_CONJURE_EARTH_ELEMENTAL)  // SPPR702.SPL (Erdelementar beschwören)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(NearestEnemyOf(Myself),CLERIC_CONJURE_EARTH_ELEMENTAL)  // SPPR702.SPL (Erdelementar beschwören)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flammenschlag)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(NearestEnemyOf(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flammenschlag)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(NearestEnemyOf(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Mantel der Furcht)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Mantel der Furcht)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_PHYSICAL_MIRROR)  // SPPR613.SPL (Materiespiegel)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,CLERIC_PHYSICAL_MIRROR)  // SPPR613.SPL (Materiespiegel)
END

IF
    See(NearestEnemyOf(Myself))
    !Range(NearestEnemyOf(Myself),7)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        EquipRanged()
        AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
    See(NearestEnemyOf(Myself))
    Range(NearestEnemyOf(Myself),7)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        EquipMostDamagingMelee()
        AttackReevaluate(NearestEnemyOf(Myself),45)
END

