IF
    Clicked([ANYONE])
    Range(LastTrigger,10)
    Global("Statue","ACIL4O",0)
THEN
    RESPONSE #100
        CreateCreatureImpassable("AC#4OGOL",[408.206],SEE)  // Verwitterte Zwergenstatue
        SetGlobal("Statue","ACIL4O",1)
        ActionOverride("AC#4OGOL",StartDialogueNoSet([PC]))
END

IF
    Clicked([ANYONE])
    Range(LastTrigger,10)
    Global("Statue","ACIL4O",1)
THEN
    RESPONSE #100
        ActionOverride("AC#4OGOL",StartDialogueNoSet([PC]))
END

IF
    Clicked([ANYONE])
    !Range(LastTrigger,10)
THEN
    RESPONSE #100
        DisplayString(Myself,14702)  // Ihr seid zu weit entfernt, um das zu benutzen.
END

