IF
	Die()
THEN
	RESPONSE #100
		ReallyForceSpellDead(Myself,ILLUSION_DEATH)  // SPIN835.SPL (No such index)
		Wait(1)
		DestroySelf()
END

IF
	See(Player1)
	HasItem("AC#SWTET",Player1)
	!Race(Player1,ELF)
THEN
	RESPONSE #100
		AttackReevaluate(Player1,15)
END

IF
	See(Player2)
	HasItem("AC#SWTET",Player2)
	!Race(Player2,ELF)
THEN
	RESPONSE #100
		AttackReevaluate(Player2,15)
END

IF
	See(Player3)
	HasItem("AC#SWTET",Player3)
	!Race(Player2,ELF)
THEN
	RESPONSE #100
		AttackReevaluate(Player3,15)
END

IF
	See(Player4)
	HasItem("AC#SWTET",Player4)
	!Race(Player4,ELF)
THEN
	RESPONSE #100
		AttackReevaluate(Player4,15)
END

IF
	See(Player5)
	HasItem("AC#SWTET",Player5)
	!Race(Player5,ELF)
THEN
	RESPONSE #100
		AttackReevaluate(Player5,15)
END

IF
	See(Player6)
	HasItem("AC#SWTET",Player6)
	!Race(Player6,ELF)
THEN
	RESPONSE #100
		AttackReevaluate(Player6,15)
END

IF
	See(NearestEnemyOf(Myself))
	Delay(15)
THEN
	RESPONSE #100
		ApplySpell(Myself,CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Schutz vor Bösem)
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),30)
		Continue()
END

IF
	AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		Attack(LastAttackerOf(Myself))
		Continue()
END

IF
	Detect(NearestEnemyOf(Myself))
	!See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),40)
	HaveSpell(INQUIS_TRUE_SIGHT)  // SPCL232.SPL (Wahrer Blick)
THEN
	RESPONSE #100
		Spell(Myself,INQUIS_TRUE_SIGHT)  // SPCL232.SPL (Wahrer Blick)
		Continue()
END

IF
	HPPercentLT(Myself,50)
	HaveSpell(PALADIN_LAY_ON_HANDS)  // SPCL211.SPL (Hände auflegen)
THEN
	RESPONSE #100
		Spell(Myself,PALADIN_LAY_ON_HANDS)  // SPCL211.SPL (Hände auflegen)
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	OR(6)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_BLESS)
		StateCheck(LastSeenBy(Myself),STATE_CHANT)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_BLUR)
		HasImmunityEffects(LastSeenBy(Myself))
	HaveSpell(INQUIS_DISPEL_MAGIC)  // SPCL231.SPL (Magie bannen)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),INQUIS_DISPEL_MAGIC)  // SPCL231.SPL (Magie bannen)
		Continue()
END

