IF
	Global("prepspells","LOCALS",0)
	See(NearestEnemyOf(Myself))
	See(NearestMyGroupOfType)
THEN
	RESPONSE #100
		SetGlobal("prepspells","LOCALS",1)
		ForceSpell(Myself,WIZARD_MISLEAD)  // SPWI607.SPL (Ablenkung)
		DisplayString(Myself,31247)  // Tattoo der Macht: Immunität gegen Zauber
		ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_INVOCATION)  // SPWI595.SPL (Immunität gegen Zauber: Hervorrufung)
		Spell(LastSeenBy(Myself),WIZARD_HASTE)  // SPWI305.SPL (Hast)
END

IF
	Allegiance(Myself,ENEMY)
	See([GOODCUTOFF.0.0.0.0.SUMMONED])
	!Range(LastSeenBy(Myself),12)
	HaveSpell(WIZARD_DISPEL_MAGIC)  // SPWI302.SPL (Magie bannen)
	Global("DeathSpell","LOCALS",0)
THEN
	RESPONSE #100
		DisplayString(Myself,31024)  // Magisches Tattoo: Spiegelbild
		ApplySpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Spiegelbild)
		ForceSpell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Todeszauber)
		SetGlobal("DeathSpell","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	Global("prepspells","LOCALS",1)
	CheckStatLT(Myself,1,STONESKINS)
	TookDamage()
THEN
	RESPONSE #100
		DisplayString(Myself,29736)  // Notfall: Steinhaut
		ApplySpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Steinhaut)
		SetGlobal("prepspells","LOCALS",2)
END

IF
	Allegiance(Myself,ENEMY)
	See(StrongestOf([PC]))
	HaveSpell(WIZARD_MAZE)  // SPWI813.SPL (Irrgarten)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_MAZE)  // SPWI813.SPL (Irrgarten)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (Größeres Unbehagen)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
THEN
	RESPONSE #100
		Spell(SecondNearestEnemyOf(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Größeres Unbehagen)
		Spell(SecondNearestEnemyOf(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_DEATH_SPELL)  // SPWI605.SPL (Todeszauber)
THEN
	RESPONSE #100
		Spell(SecondNearestEnemyOf(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Todeszauber)
END

IF
	Allegiance(Myself,ENEMY)
	See([GOODCUTOFF.0.0.0.0.SUMMONED])
	Range(LastSeenBy(Myself),12)
	HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Kleinere Kugel der Unverwundbarkeit)
THEN
	RESPONSE #100
		DisplayString(Myself,31024)  // Magisches Tattoo: Spiegelbild
		ApplySpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Spiegelbild)
		Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Kleinere Kugel der Unverwundbarkeit)
END

IF
	HaveSpell(WIZARD_SUMMON_NISHRUU)  // SPWI624.SPL (Nishruu beschwören)
	OR(3)
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_SUMMON_NISHRUU)  // SPWI624.SPL (Nishruu beschwören)
END

IF
	Global("prepspells","LOCALS",2)
	HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Steinhaut)
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Steinhaut)
END

IF
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Magie durchdringen)
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Wort der Macht: Stille)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Magie durchdringen)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Wort der Macht: Stille)
END

IF
	Allegiance(Myself,ENEMY)
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Wort der Macht: Betäubung)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Wort der Macht: Betäubung)
END

IF
	Allegiance(Myself,ENEMY)
	!Range(FourthNearestEnemyOf(Myself),10)
	HaveSpell(WIZARD_FIREBALL)  // SPWI304.SPL (Feuerball)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (Feuerball)
END

IF
	See(NearestEnemyOf(Myself))
	HasItem("SCRL9G",Myself)  // Abi Dalzims Abscheuliche Austrocknung
THEN
	RESPONSE #100
		UseItem("SCRL9G",LastSeenBy(Myself))  // Abi Dalzims Abscheuliche Austrocknung
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Monster festhalten)
THEN
	RESPONSE #100
		Spell(ThirdNearestEnemyOf(Myself),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Monster festhalten)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MONSTER_SUMMONING_3)  // SPWI504.SPL (Monster herbeirufen 3)
THEN
	RESPONSE #100
		Spell(ThirdNearestEnemyOf(Myself),WIZARD_MONSTER_SUMMONING_3)  // SPWI504.SPL (Monster herbeirufen 3)
END

IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Geheimes Wort)
	HaveSpell(WIZARD_DISINTEGRATE)  // SPWI616.SPL (Auflösung)
	HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Spiegelbild)
THEN
	RESPONSE #10
		Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Spiegelbild)
		Spell(NearestEnemyOf(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Geheimes Wort)
		Spell(NearestEnemyOf(Myself),WIZARD_DISINTEGRATE)  // SPWI616.SPL (Auflösung)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_SPELL_TURNING)  // SPWI701.SPL (Zauber zurückwerfen)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Zauber zurückwerfen)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Blitzstrahl)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Blitzstrahl)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flammenpfeil)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flammenpfeil)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melfs Säurepfeil)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melfs Säurepfeil)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magisches Geschoß)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magisches Geschoß)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Farbkugel)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Farbkugel)
END

IF
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
		ActionOverride("AC#78PRI",Enemy())
		ActionOverride("AC#78HAM",Enemy())
		ActionOverride("AC#78FAM",Enemy())
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		Attack(LastAttackerOf(Myself))
END

