IF
	Clicked([ANYONE])
	!Range(LastTrigger,12)
THEN
	RESPONSE #100
		DisplayString(Myself,@359) // Aus dieser Entfernung könnt Ihr nichts erkennen.
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	OR(2)
		Race(LastTrigger,ELF)
		Race(LastTrigger,HALF_ELF)
THEN
	RESPONSE #100
		DisplayString(Myself,@946)
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	CheckStatGT(LastTrigger,70,LORE)

THEN
	RESPONSE #100
		DisplayString(Myself,@946)
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	CheckStatLT(LastTrigger,71,LORE)

THEN
	RESPONSE #100
		DisplayString(Myself,@947)
END

