IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
THEN
	RESPONSE #100
                ClearAllActions()
		StartCutSceneMode()
		CreateVisualEffectObject("SPGFLSH1",LastTrigger)
		CreateVisualEffectObject("SPGRWHRL",Player1)
		CreateVisualEffectObject("SPGFLSH1",Player2)
		CreateVisualEffectObject("SPGRWHRL",Player3)
		CreateVisualEffectObject("SPGFLSH1",Player4)
		CreateVisualEffectObject("SPGFLSH1",Player5)
		CreateVisualEffectObject("SPGFLSH1",Player6)
		PlaySound("EFF_M63")
		Wait(1)
		ActionOverride(Player1,JumpToPoint([1029.1675]))
                ActionOverride(Player2,JumpToPoint([1029.1675]))
                ActionOverride(Player3,JumpToPoint([1029.1675]))
                ActionOverride(Player4,JumpToPoint([1029.1675]))
                ActionOverride(Player5,JumpToPoint([1029.1675]))
                ActionOverride(Player6,JumpToPoint([1029.1675]))
		MoveViewPoint([1029.1675],INSTANT)
		PlaySound("EFF_M63")
		CreateVisualEffectObject("SPGRWHRL",Player1)
		Wait(1)
		EndCutSceneMode()
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,10)
THEN
	RESPONSE #100
		DisplayString(Myself,14702)
END


