IF
	Clicked([ANYONE])
	Range(LastTrigger,15)
        Global("Githrune01","ACIL81",0)
THEN
	RESPONSE #100
	         SetGlobal("Githrune01","ACIL81",1)
		 DisplayString(Myself,@917)
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,15)
	PartyHasItem("AC#GIRU1")
	Global("Githrune01","ACIL81",1)
THEN
	RESPONSE #100
                SetGlobal("Githrune01","ACIL81",2)
                TakePartyItem("AC#GIRU1")
                PlaySound("EFF_M62")
                AmbientActivate("Rune01",TRUE)
                DisplayString(Myself,@916)
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,15)
        !PartyHasItem("AC#GIRU1")
THEN
	RESPONSE #100
		DisplayString(Myself,@917)
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,15)
THEN
	RESPONSE #100
		DisplayString(Myself,14702)
END




