IF
	Clicked([ANYONE])
	Race(LastTrigger,DWARF)
THEN
	RESPONSE #100
		DisplayString(Myself,@30)
END

IF
	Clicked([ANYONE])
	CheckStatGT(LastTrigger,50,LORE)

THEN
	RESPONSE #100
		DisplayString(Myself,@31)
END

/*
IF
	Clicked([ANYONE])
	PartyHasItemIdentified("AC#BKDWF") // Die Schrift und Sprache der Zwerge

THEN
	RESPONSE #100
		DisplayString(Myself,@31)
END
*/

IF
	Clicked([ANYONE])
	CheckStatLT(LastTrigger,51,LORE)

THEN
	RESPONSE #100
		DisplayString(Myself,@32)
END

