IF
	Global("AC#90RUD","ACIL90",0)
	Contains("AC#90RUD",Myself)  // Zwergen-Runentafel
THEN
	RESPONSE #100
		SetGlobal("AC#90RUD","ACIL90",1)
		IncrementGlobal("FlashCounter","ACIL90",1)
		CreateVisualEffect("AC#ELECT",[1741.676])
END

IF
	Contains("AC#90RUD",Myself)   // Zwergen-Runentafel
	GlobalLT("FlashCounter","ACIL90",8)
	RandomNum(10,1)
THEN
	RESPONSE #100
		CreateVisualEffect("AC#ELECT",[1741.676])
END