IF
	AttackedBy([ANYONE],DEFAULT)
	HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Steinhaut)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Steinhaut)
END

IF
	AttackedBy([ANYONE],DEFAULT)
	HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Spiegelbild)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Spiegelbild)
END

IF
	See(NearestEnemyOf(Myself))
	Global("Teleport","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Teleport","LOCALS",1)
		SetGlobalTimer("TeleportTimer","LOCALS",THREE_ROUNDS)
END

IF
	Global("Teleport","LOCALS",2)
	GlobalLT("TeleportatonCycle","LOCALS",5)
THEN
	RESPONSE #100
		SetGlobal("Teleport","LOCALS",1)
		IncrementGlobal("TeleportatonCycle","LOCALS",1)
END

IF
	See(NearestEnemyOf(Myself))
	GlobalTimerExpired("TeleportTimer","LOCALS")
	Global("Teleport","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Teleport","LOCALS",2)
		SetGlobalTimer("Teleport","LOCALS",THREE_ROUNDS)
		ReallyForceSpellRES("AC#TEL1",Myself)  // Teleportieren
		Wait(1)
		JumpToPoint([1613.1531])
	RESPONSE #100
		SetGlobal("Teleport","LOCALS",2)
		SetGlobalTimer("Teleport","LOCALS",THREE_ROUNDS)
		ReallyForceSpellRES("AC#TEL1",Myself)  // Teleportieren
		Wait(1)
		JumpToPoint([1807.1956])
	RESPONSE #100
		SetGlobal("Teleport","LOCALS",2)
		SetGlobalTimer("Teleport","LOCALS",THREE_ROUNDS)
		ReallyForceSpellRES("AC#TEL1",Myself)  // Teleportieren
		Wait(1)
		JumpToPoint([2759.1803])
	RESPONSE #100
		SetGlobal("Teleport","LOCALS",2)
		SetGlobalTimer("Teleport","LOCALS",THREE_ROUNDS)
		ReallyForceSpellRES("AC#TEL1",Myself)  // Teleportieren
		Wait(1)
		JumpToPoint([2295.1245])
END

IF
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	Global("firstStun","LOCALS",0)
THEN
	RESPONSE #100
		ForceSpell(NearestEnemyOf(Myself),MIND_FLAYER_PSIONIC_BLAST)  // SPIN974.SPL (Psi-Schlag)
		SetGlobal("firstStun","LOCALS",1)
		IncrementGlobal("MindFlayerBehavior","LOCALS",1)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_FIREBALL)  // SPWI304.SPL (Feuerball)
	!GlobalTimerNotExpired("SpellTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("SpellTimer","LOCALS",ONE_ROUND)
		Spell(NearestEnemyOf(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (Feuerball)
	RESPONSE #100
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Blitzstrahl)
	!GlobalTimerNotExpired("SpellTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("SpellTimer","LOCALS",ONE_ROUND)
		Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Blitzstrahl)
	RESPONSE #100
		Continue()
END

IF
	See([PC])
	Allegiance(Myself,ENEMY)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!GlobalTimerNotExpired("SpellTimer","LOCALS")
THEN
	RESPONSE #50
		ForceSpell(LastSeenBy(Myself),MIND_FLAYER_DOMINATION)  // SPIN975.SPL (Paranormale Beherrschung)
		SetGlobalTimer("SpellTimer","LOCALS",ONE_ROUND)
		SetGlobal("MindFlayerBehavior","LOCALS",1)
END

IF
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("SpellTimer","LOCALS")
THEN
	RESPONSE #100
		ForceSpell(NearestEnemyOf(Myself),MIND_FLAYER_PSIONIC_BLAST)  // SPIN974.SPL (Psi-Schlag)
		SetGlobalTimer("SpellTimer","LOCALS",ONE_ROUND)
		IncrementGlobal("MindFlayerBehavior","LOCALS",1)
END

IF
	HPPercentLT(Myself,100)
	AttackedBy([ANYONE],DEFAULT)
	Delay(9)
THEN
	RESPONSE #100
		ForceSpell(LastAttackerOf(Myself),MIND_FLAYER_PSIONIC_BLAST)  // SPIN974.SPL (Psi-Schlag)
		IncrementGlobal("MindFlayerBehavior","LOCALS",1)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck([PC],STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate([PC],45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(SecondNearest([PC]),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(SecondNearest([PC]),45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(ThirdNearest([PC]),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(ThirdNearest([PC]),45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(FourthNearest([PC]),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(FourthNearest([PC]),45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(FifthNearest([PC]),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(FifthNearest([PC]),45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(SixthNearest([PC]),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(SixthNearest([PC]),45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(SecondNearestEnemyOf(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(ThirdNearestEnemyOf(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(FourthNearestEnemyOf(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(FifthNearestEnemyOf(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
THEN
	RESPONSE #100
		AttackReevaluate(SixthNearestEnemyOf(Myself),45)
END

