IF
    See(NearestEnemyOf(Myself))
    Global("RemoveMagic","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(Myself,DRAGON_STONE_SKIN)  // SPIN694.SPL (Steinhaut)
        ForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Magie zerstören)
        SetGlobal("StoneSkin","LOCALS",1)
        SetGlobal("RemoveMagic","LOCALS",1)
END

IF
    !Detect([PC])
    HPLT(Myself,50)
    CombatCounter(0)
THEN
    RESPONSE #100
        SetGlobal("RemoveMagic","LOCALS",0)
        SetGlobal("WingBuffet","LOCALS",0)
        SetGlobal("Haste","LOCALS",0)
        SetGlobal("DRAGONFEAR","LOCALS",0)
        ForceSpell(Myself,CLERIC_HEAL)  // SPPR607.SPL (Heilung)
END

IF
    See(NearestEnemyOf(Myself))
    Global("DRAGONFEAR","LOCALS",0)
THEN
    RESPONSE #100
        ReallyForceSpell(NearestEnemyOf(Myself),DRAGON_FEAR)  // SPIN895.SPL (Drachenfurcht)
        ReallyForceSpell(NearestEnemyOf(Myself),DRAGON_LOWER_FIRE)  // SPIN682.SPL (Feuerresistenz senken)
        SetGlobal("DRAGONFEAR","LOCALS",1)
        SetGlobalTimer("A#ILCHARVBREATH","GLOBAL",1)
        ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Flügelschlag)
END

IF
    GlobalTimerExpired("A#ILCHARVBREATH","GLOBAL")
    See(NearestEnemyOf(Myself))
    Range(LastSeenBy(Myself),11)
    Global("WingBuffet","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Flügelschlag)
        Wait(1)
        SetGlobal("WingBuffet","LOCALS",1)
    RESPONSE #60
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    !Range(LastSeenBy(Myself),10)
    GlobalTimerExpired("A#IL_CHARVBREATH","GLOBAL")
THEN
    RESPONSE #100
        SetGlobal("WingBuffet","LOCALS",0)
        VerbalConstant(Myself,BATTLE_CRY)
        Wait(1)
        ForceSpell(LastSeenBy(Myself),RED_DRAGON_BREATH)  // SPIN894.SPL (Roter Drache: Odemwaffe)
        ReallyForceSpell(LastSeenBy(Myself),RED_DRAGON_HIT)  // SPIN693.SPL (No such index)
        SetGlobalTimer("A#ILCHARVBREATH","GLOBAL",THREE_ROUNDS)
END

IF
    Global("WingBuffet","LOCALS",1)
    See(NearestEnemyOf(Myself))
    Range(LastSeenBy(Myself),11)
THEN
    RESPONSE #100
        SetGlobal("WingBuffet","LOCALS",0)
        SetGlobalTimer("A#ILCHARVBREATH","GLOBAL",THREE_ROUNDS)
END

IF
    See(NearestEnemyOf(Myself))
    Global("Offense1","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Größeres Unbehagen)
        SetGlobal("Offense1","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("Haste","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(Myself,WIZARD_HASTE)  // SPWI305.SPL (Hast)
        SetGlobal("Haste","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("HoldPerson","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
        SetGlobal("HoldPerson","LOCALS",1)
END

IF
    Global("Silence","LOCALS",0)
    OR(2)
        See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
        See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),DRAGON_SILENCE)  // SPIN692.SPL (Stille: 4,5 m Radius)
        SetGlobal("Silence","LOCALS",1)
        AttackOneRound(LastSeenBy(Myself))
        AttackOneRound(LastSeenBy(Myself))
END

IF
    See(NearestEnemyOf(Myself))
    Delay(6)
    GlobalLT("CharmPerson","LOCALS",3)
THEN
    RESPONSE #100
        ForceSpell(NearestEnemyOf(Myself),WIZARD_CHARM_PERSON)  // SPWI104.SPL (Personen bezaubern)
        IncrementGlobal("CharmPerson","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(NearestEnemyOf(Myself),35)
    RESPONSE #10
        ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melfs Säurepfeil)
END

IF
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        MoveToObject(NearestEnemyOf(Myself))
END

IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        Enemy()
END

