IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        FadeToColor([30.0],150)
        Wait(1)
        LeaveAreaLUAPanic("ACIL80","AC#GTR80",[267.265],S)
        LeaveAreaLUA("ACIL80","AC#GTR80",[267.265],NW)
        ActionOverride(Player2,LeaveAreaLUA("ACIL80","AC#GTR80",[267.265],NW))
        ActionOverride(Player3,LeaveAreaLUA("ACIL80","AC#GTR80",[267.265],NW))
        ActionOverride(Player4,LeaveAreaLUA("ACIL80","AC#GTR80",[267.265],NW))
        ActionOverride(Player5,LeaveAreaLUA("ACIL80","AC#GTR80",[267.265],NW))
        ActionOverride(Player6,LeaveAreaLUA("ACIL80","AC#GTR80",[267.265],NW))
        MultiPlayerSync()
        MoveViewPoint([2701.407],INSTANT)
        Wait(1)
        FadeFromColor([30.0],150)
        ActionOverride("AC#IL801",StartDialogueNoSet(Player1))
END

