IF
	See([ENEMY.UNDEAD])
THEN
	RESPONSE #100
                 AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	See("AC#MARIL")
        !Dead("AC#MARIL")
	Global("AC#ChoseNone","ACIL81",1)
THEN
	RESPONSE #100
                 AttackReevaluate("AC#MARIL",30)
END

IF
	Die()
THEN
	RESPONSE #100
		CreateVisualEffectObject("SPHOLY",Myself)
		DestroySelf()
END

IF
	Dead("AC#MARIL")
	Global("AC#ChoseNone","ACIL81",1)
THEN
	RESPONSE #100
		SetGlobal("AC#ChoseNone","ACIL81",2)
		CreateVisualEffectObject("SPDIMNDR",Myself)
		Wait(1)
	        DestroySelf()
END