IF
    Range(NearestEnemyOf(Myself),6)
    HPPercentLT(Myself,50)
    RandomNum(3,1)
THEN
    RESPONSE #100
        RunAwayFrom(NearestEnemyOf(Myself),45)
END

IF
    Global("BeholderBehavior","LOCALS",0)
    See([GOODCUTOFF.0.0.0.0.SUMMONED])
THEN
    RESPONSE #100
        FaceObject(LastSeenBy(Myself))
        ForceSpell(LastSeenBy(Myself),BEHOLDER_PARALYZATION)  // SPIN990.SPL (Lähmung)
        Wait(3)
        Continue()
END

IF
    Global("BeholderBehavior","LOCALS",0)
    See([PC])
    HPGT(Myself,55)
THEN
    RESPONSE #100
        FaceObject(SecondNearest([PC]))
        ForceSpell(SecondNearest([PC]),BEHOLDER_FEAR)  // SPIN981.SPL (Furcht)
        Wait(2)
        Continue()
END

IF
    Global("BeholderBehavior","LOCALS",0)
    See(LeastDamagedOf(Myself))
    HPGT(Myself,45)
THEN
    RESPONSE #100
        FaceObject(LeastDamagedOf(Myself))
        ForceSpell(LeastDamagedOf(Myself),BEHOLDER_PARALYZATION)  // SPIN990.SPL (Lähmung)
        Continue()
END

IF
    Global("BeholderBehavior","LOCALS",0)
    See([PC])
    !See(LeastDamagedOf(Myself))
    HPGT(Myself,45)
THEN
    RESPONSE #100
        FaceObject([PC])
        ForceSpell([PC],BEHOLDER_PARALYZATION)  // SPIN990.SPL (Lähmung)
        Continue()
END

IF
    OR(2)
        LevelGT(Player1,11)
        DifficultyGT(NORMAL)
    Global("BeholderBehavior","LOCALS",0)
    See([PC])
    HPGT(Myself,25)
THEN
    RESPONSE #100
        FaceObject(ThirdNearest([PC]))
        ForceSpell(ThirdNearest([PC]),BEHOLDER_FLESH_TO_STONE)  // SPIN984.SPL (Fleisch zu Stein)
        Wait(2)
        Continue()
END

IF
    Global("BeholderBehavior","LOCALS",0)
    See([PC])
    See([PC.0.0.MAGE])
THEN
    RESPONSE #100
        FaceObject(LastSeenBy(Myself))
        ForceSpell(LastSeenBy(Myself),BEHOLDER_ANTIMAGIC_RAY)  // SPIN992.SPL (Antimagischer Strahl)
        SetGlobal("BeholderBehavior","LOCALS",1)
        Wait(2)
END

IF
    Global("BeholderBehavior","LOCALS",0)
    See([PC])
    !See([PC.0.0.MAGE])
THEN
    RESPONSE #100
        FaceObject([PC])
        ForceSpell([PC],BEHOLDER_ANTIMAGIC_RAY)  // SPIN992.SPL (Antimagischer Strahl)
        SetGlobal("BeholderBehavior","LOCALS",1)
        Wait(2)
END

IF
    Global("BeholderBehavior","LOCALS",1)
    See([GOODCUTOFF.0.0.0.0.SUMMONED])
THEN
    RESPONSE #100
        FaceObject(LastSeenBy(Myself))
        ForceSpell(LastSeenBy(Myself),BEHOLDER_PARALYZATION)  // SPIN990.SPL (Lähmung)
        Wait(3)
        Continue()
END

IF
    Global("BeholderBehavior","LOCALS",1)
    See([PC])
    HPGT(Myself,35)
THEN
    RESPONSE #100
        FaceObject(SecondNearest([PC]))
        ForceSpell(SecondNearest([PC]),BEHOLDER_SLOW)  // SPIN983.SPL (Verlangsamen)
        Wait(2)
        Continue()
END

IF
    Global("BeholderBehavior","LOCALS",1)
    See([PC])
    HPGT(Myself,5)
THEN
    RESPONSE #100
        FaceObject(ThirdNearest([PC]))
        ForceSpell(LeastDamagedOf(Myself),HIVE_MOTHER_CAUSE_SERIOUS_WOUNDS)  // SPIN551.SPL (Schwere Wunden verursachen)
        Wait(2)
        Continue()
END

IF
    OR(2)
        LevelGT(Player1,11)
        DifficultyGT(NORMAL)
    Global("BeholderBehavior","LOCALS",1)
    See(LeastDamagedOf(Myself))
THEN
    RESPONSE #100
        FaceObject(LeastDamagedOf(Myself))
        ForceSpell(LeastDamagedOf(Myself),BEHOLDER_DEATH_RAY)  // SPIN991.SPL (Todesstrahl)
        Continue()
END

IF
    OR(2)
        LevelGT(Player1,11)
        DifficultyGT(NORMAL)
    Global("BeholderBehavior","LOCALS",1)
    See([PC])
    !See(LeastDamagedOf(Myself))
THEN
    RESPONSE #100
        FaceObject([PC])
        ForceSpell([PC],BEHOLDER_DEATH_RAY)  // SPIN991.SPL (Todesstrahl)
        Continue()
END

IF
    Global("BeholderBehavior","LOCALS",1)
    See([PC])
    See([PC.0.0.MAGE])
THEN
    RESPONSE #100
        FaceObject(LastSeenBy(Myself))
        ForceSpell(LastSeenBy(Myself),BEHOLDER_ANTIMAGIC_RAY)  // SPIN992.SPL (Antimagischer Strahl)
        SetGlobal("BeholderBehavior","LOCALS",0)
        Wait(2)
END

IF
    Global("BeholderBehavior","LOCALS",1)
    See([PC])
    !See([PC.0.0.MAGE])
THEN
    RESPONSE #100
        FaceObject([PC])
        ForceSpell([PC],BEHOLDER_ANTIMAGIC_RAY)  // SPIN992.SPL (Antimagischer Strahl)
        SetGlobal("BeholderBehavior","LOCALS",0)
        Wait(2)
END

