/*
IF
    NumberOfTimesTalkedTo(0)
THEN
    RESPONSE #100
        StartDialogueNoSet(LastSeenBy(Myself))
END
*/

IF
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        Enemy()
END

IF
    !Detect([PC])
    HPLT(Myself,50)
    CombatCounter(0)
THEN
    RESPONSE #100
        SetGlobal("RemoveMagic","LOCALS",0)
        SetGlobal("WingBuffet","LOCALS",0)
        SetGlobal("Haste","LOCALS",0)
        SetGlobal("DRAGONFEAR","LOCALS",0)
        ForceSpell(Myself,CLERIC_HEAL)  // SPPR607.SPL (Heilung)
END

IF
    See(NearestEnemyOf(Myself))
    Global("DRAGONFEAR","LOCALS",0)
THEN
    RESPONSE #100
        ReallyForceSpell(NearestEnemyOf(Myself),DRAGON_FEAR)  // SPIN895.SPL (Drachenfurcht)
        SetGlobal("DRAGONFEAR","LOCALS",1)
        SetGlobalTimer("SHADOWDRAGONBREATH","GLOBAL",1)
        ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Flügelschlag)
END

IF
    GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
    See(NearestEnemyOf(Myself))
    Range(LastSeenBy(Myself),11)
    Global("WingBuffet","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Flügelschlag)
        Wait(3)
        SetGlobal("WingBuffet","LOCALS",1)
    RESPONSE #60
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    !Range(LastSeenBy(Myself),10)
    GlobalTimerExpired("SHADOWDRAGONBREATH","GLOBAL")
THEN
    RESPONSE #100
        SetGlobal("WingBuffet","LOCALS",0)
        ForceSpellRES("AC#IL71",LastSeenBy(Myself))  // Drachenalb-Odem
        ReallyForceSpellRES("spin893v",LastSeenBy(Myself))  // No such index
        SetGlobalTimer("SHADOWDRAGONBREATH","GLOBAL",THREE_ROUNDS)
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(NearestEnemyOf(Myself),35)
END

IF
    Allegiance(Myself,ENEMY)
    !See([ANYONE])
THEN
    RESPONSE #100
        MoveToObject(Player1)
END

IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        Enemy()
END

