IF
    See(NearestEnemyOf(Myself))
    Global("DRAGONFEAR","LOCALS",0)
THEN
    RESPONSE #100
        ReallyForceSpell(NearestEnemyOf(Myself),DRAGON_FEAR)  // SPIN895.SPL (Drachenfurcht)
        SetGlobal("DRAGONFEAR","LOCALS",1)
        SetGlobalTimer("REDDRAGONBREATH","GLOBAL",1)
END

IF
    GlobalTimerExpired("REDDRAGONBREATH","GLOBAL")
    See(NearestEnemyOf(Myself))
    Range(LastSeenBy(Myself),11)
    Global("WingBuffet","LOCALS",0)
THEN
    RESPONSE #100
        Wait(1)
        SetGlobal("WingBuffet","LOCALS",1)
    RESPONSE #60
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    !Range(LastSeenBy(Myself),10)
    GlobalTimerExpired("REDDRAGONBREATH","GLOBAL")
THEN
    RESPONSE #100
        SetGlobal("WingBuffet","LOCALS",0)
        ForceSpell(LastSeenBy(Myself),RED_DRAGON_BREATH)  // SPIN894.SPL (Roter Drache: Odemwaffe)
        ReallyForceSpellRES("AC#RDRJ",LastSeenBy(Myself))  // No such index
        SetGlobalTimer("REDDRAGONBREATH","GLOBAL",THREE_ROUNDS)
END

IF
    Global("WingBuffet","LOCALS",1)
    See(NearestEnemyOf(Myself))
    Range(LastSeenBy(Myself),11)
THEN
    RESPONSE #100
        SetGlobal("WingBuffet","LOCALS",0)
        SetGlobalTimer("REDDRAGONBREATH","GLOBAL",THREE_ROUNDS)
END

IF
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        MoveToObject(NearestEnemyOf(Myself))
END

IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        Enemy()
END

