IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        Shout(89)
        Enemy()
END

IF
    HitBy([GOODCUTOFF],CRUSHING)
THEN
    RESPONSE #100
        Shout(89)
        Continue()
END

IF
    OR(5)
        AttackedBy([PC],DEFAULT)
        AttackedBy([FAMILIAR],DEFAULT)
        AttackedBy([ALLY],DEFAULT)
        AttackedBy([CONTROLLED],DEFAULT)
        AttackedBy([CHARMED],DEFAULT)
    Allegiance(Myself,ENEMY)
    ActionListEmpty()
THEN
    RESPONSE #100
        Shout(89)
        Continue()
END

IF
    Heard([ANYONE],89)
    Allegiance(Myself,NEUTRAL)
    !Class(Myself,INNOCENT)
THEN
    RESPONSE #100
        Enemy()
        MoveToObject(LastHeardBy(Myself))
END

IF
    Heard([ANYONE],89)
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        Enemy()
END

IF
    Heard([ANYONE],89)
    !Class(Myself,INNOCENT)
    !See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        MoveToObject(LastHeardBy(Myself))
        Continue()
END

IF
    Global("Prepared","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Prepared","LOCALS",1)
        ApplySpellRES("SPCL151",Myself)  // No such index
END

IF
    AttackedBy([ANYONE],DEFAULT)
    HPPercentLT(Myself,50)
    Global("Blurred","LOCALS",0)
THEN
    RESPONSE #100
        ReallyForceSpellRES("SPWI201",Myself)  // Verschwimmen
        SetGlobal("Blurred","LOCALS",1)
END

