IF
    GlobalGT("AC#25_LolthPriestess","GLOBAL",2)
    Global("AC#25PactLolthPriestess","GLOBAL",0)
THEN
    RESPONSE #100
        CreateVisualEffectObject("SPDIMNDR",Myself)
        Wait(1)
        DestroySelf()
END

IF
    Global("AC#25PactLolthPriestess","GLOBAL",10)
THEN
    RESPONSE #100
        CreateVisualEffectObject("SPDIMNDR",Myself)
        Wait(1)
        DestroySelf()
END

IF
    Allegiance(Myself,ENEMY)
    See(NearestEnemyOf(Myself))
    See(SixthNearest([GOODCUTOFF]))
    Global("Ambush06","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Ambush06","LOCALS",1)
        CreateCreatureObjectEffect("AC#DROW7","AC#ILSH2",SixthNearest([GOODCUTOFF]))  // Drow
        Continue()
END

IF
    Allegiance(Myself,ENEMY)
    See(NearestEnemyOf(Myself))
    See(FifthNearest([GOODCUTOFF]))
    Global("Ambush05","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Ambush05","LOCALS",1)
        CreateCreatureObjectEffect("AC#DROW7","AC#ILSH2",FifthNearest([GOODCUTOFF]))  // Drow
        Continue()
END

IF
    Allegiance(Myself,ENEMY)
    See(NearestEnemyOf(Myself))
    See(FourthNearest([GOODCUTOFF]))
    Global("Ambush04","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Ambush04","LOCALS",1)
        CreateCreatureObjectEffect("AC#DROW7","AC#ILSH2",FourthNearest([GOODCUTOFF]))  // Drow
        Continue()
END

IF
    Allegiance(Myself,ENEMY)
    See(NearestEnemyOf(Myself))
    See(ThirdNearest([GOODCUTOFF]))
    Global("Ambush03","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Ambush03","LOCALS",1)
        CreateCreatureObjectEffect("AC#DROW7","AC#ILSH2",ThirdNearest([GOODCUTOFF]))  // Drow
        Continue()
END

IF
    Allegiance(Myself,ENEMY)
    See(NearestEnemyOf(Myself))
    See(SecondNearest([GOODCUTOFF]))
    Global("Ambush02","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Ambush02","LOCALS",1)
        CreateCreatureObjectEffect("AC#DROW7","AC#ILSH2",SecondNearest([GOODCUTOFF]))  // Drow
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    Global("SANCTUARY","LOCALS",0)
    !StateCheck(Myself,STATE_INVISIBLE)
    !CheckStat(Myself,1,SANCTUARY)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("SANCTUARY","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        ReallyForceSpell(Myself,CLERIC_SANCTUARY)  // SPPR109.SPL (Heiligtum)
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_SANCTUARY)  // SPPR109.SPL (Heiligtum)
    !StateCheck(Myself,STATE_INVISIBLE)
    !CheckStat(Myself,1,SANCTUARY)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,CLERIC_SANCTUARY)  // SPPR109.SPL (Heiligtum)
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
    Global("SummonDemon","LOCALS",0)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("SummonDemon","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        ForceSpellRES("AC#IL73",Myself)  // Tor
        SetInterrupt(TRUE)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_BLADE_BARRIER)  // SPPR603.SPL (Klingenbarierre)
    Global("blade","LOCALS",0)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,NPC_BLADE_BARRIER)  // SPPR698.SPL (Klingenbarierre)
        SetGlobal("blade","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
END

IF
    HaveSpell(CLERIC_SILENCE_15_FOOT)  // SPPR211.SPL (Stille: 4,5 m Radius)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    OR(2)
        See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
        See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)  // SPPR211.SPL (Stille: 4,5 m Radius)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
END

IF
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Geistige Beherrschung)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Geistige Beherrschung)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
END

IF
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),6)
END

