IF
    Global("BattleBegun","LOCALS",0)
    OR(4)
        Detect([GOODCUTOFF])
        Detect(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
        CheckStatLT(Myself,55,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobal("BattleBegun","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("DRAGONFEAR","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("DRAGONFEAR","LOCALS",TWENTY_MINUTES)
        PlaySound("BLACK01")
        ReallyForceSpell(NearestEnemyOf(Myself),DRAGON_FEAR)  // SPIN895.SPL (Drachenfurcht)
        ReallyForceSpell(NearestEnemyOf(Myself),0)
        ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Flügelschlag)
END

IF
    OR(3)
        SpellCast([GOODCUTOFF],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Flammende Wolke)
        SpellCast([GOODCUTOFF],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinkende Wolke)
        SpellCast([GOODCUTOFF],WIZARD_DEATH_FOG)  // SPWI614.SPL (Tödlicher Nebel)
    !GlobalTimerNotExpired("WINGBUFFET","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("WINGBUFFET","LOCALS",8)
        ApplySpell(Myself,0)
        ForceSpell(NearestEnemyOf(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Flügelschlag)
END

IF
    !Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        NoAction()
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        Continue()
END

IF
    OR(3)
        See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
        See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
        See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
THEN
    RESPONSE #100
        Continue()
END

IF
    OR(3)
        See(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
THEN
    RESPONSE #100
        Continue()
END

IF
    OR(2)
        See(ThirdNearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
        See(ThirdNearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
THEN
    RESPONSE #100
        Continue()
END

IF
    OR(2)
        See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
        See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    !StateCheck(LastSeenBy(Myself),STATE_PANIC)
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
THEN
    RESPONSE #100
        Continue()
END

IF
    OR(2)
        See(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    !StateCheck(LastSeenBy(Myself),STATE_PANIC)
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
THEN
    RESPONSE #100
        Continue()
END

IF
    AttackedBy([ANYONE],DEFAULT)
    See(LastAttackerOf(Myself))
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    !StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
    RESPONSE #100
        Continue()
END

IF
    Range(NearestEnemyOf(Myself),4)
    See(NearestEnemyOf(Myself))
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    !StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
    RESPONSE #100
        Continue()
END

IF
    !Allegiance(LastSeenBy(Myself),GOODCUTOFF)
    See([GOODCUTOFF])
THEN
    RESPONSE #100
        MoveToObject([GOODCUTOFF])
END

IF
    OR(2)
        !Allegiance(LastSeenBy(Myself),GOODCUTOFF)
        !See([GOODCUTOFF])
    !HPPercentLT(Myself,50)
    Global("BattleBegun","LOCALS",1)
THEN
    RESPONSE #100
        RandomWalkContinuous()
END

IF
    OR(2)
        !Allegiance(LastSeenBy(Myself),GOODCUTOFF)
        !See([GOODCUTOFF])
    !HPPercentLT(Myself,50)
    Global("BattleBegun","LOCALS",0)
THEN
    RESPONSE #100
        NoAction()
END

IF
    !GlobalTimerNotExpired("WINGBUFFET","LOCALS")
    Range(LastSeenBy(Myself),10)
    RandomNum(2,1)
THEN
    RESPONSE #100
        SetGlobalTimer("WINGBUFFET","LOCALS",8)
        ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)  // SPIN695.SPL (Flügelschlag)
        Wait(1)
END

IF
    !Range(LastSeenBy(Myself),10)
    !GlobalTimerNotExpired("GREENDRAGONBREATH","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("GREENDRAGONBREATH","LOCALS",8)
        ForceSpellRES("AC#ILPB",LastSeenBy(Myself))  // SPIN535.SPL (Grüner Drachenodem)
        ReallyForceSpellRES("AC#ILPH",LastSeenBy(Myself))  // No such index
END

IF
    !GlobalTimerNotExpired("dbOffense1","LOCALS")
    RandomNum(2,1)
    OR(5)
        Class(LastSeenBy(Myself),DRUID_ALL)
        Class(LastSeenBy(Myself),CLERIC_ALL)
        Class(LastSeenBy(Myself),BARD_ALL)
        Class(LastSeenBy(Myself),MAGE_ALL)
        Class(LastSeenBy(Myself),SORCERER)
    !CheckStatGT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),BLACK_DRAGON_INSECT)  // SPIN689.SPL (Insekten herbeirufen)
        SetGlobalTimer("dbOffense1","LOCALS",21)
END

IF
    True()
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(LastSeenBy(Myself),30)
END

