IF
    See(NearestEnemyOf(Myself))
    !StateCheck(Myself,STATE_INVISIBLE)
    !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
    !Difficulty(EASIEST)
    Range(LastSeenBy(Myself),30)
    RandomNum(2,1)
    !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    !StateCheck(LastSeenBy(Myself),STATE_PANIC)
    !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
    !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
    !GlobalTimerNotExpired("Charm","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("Charm","LOCALS",ONE_ROUND)
        SpellNoDec(NearestEnemyOf(Myself),ERINYES_CHARM)  // SPIN558.SPL (Personen bezaubern)
END

IF
    See(NearestEnemyOf(Myself))
    OR(2)
        Range(NearestEnemyOf(Myself),10)
        HPPercentLT(Myself,50)
    !StateCheck(Myself,STATE_INVISIBLE)
    !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
    !GlobalTimerNotExpired("Invis","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("Invis","LOCALS",TWO_ROUNDS)
        ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Verbesserte Unsichtbarkeit)
END

IF
    HPPercentLT(Myself,50)
    OR(2)
        StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
        StateCheck(Myself,STATE_INVISIBLE)
    Range(NearestEnemyOf(Myself),12)
THEN
    RESPONSE #100
        SetGlobal("running","LOCALS",1)
        RunAwayFrom(NearestEnemyOf(Myself),30)
END

IF
    See(NearestEnemyOf(Myself))
    !Range(LastSeenBy(Myself),20)
THEN
    RESPONSE #100
        EquipRanged()
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
    See(NearestEnemyOf(Myself))
    Range(LastSeenBy(Myself),20)
    HPPercentGT(Myself,50)
    OR(2)
        StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
        StateCheck(Myself,STATE_INVISIBLE)
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
    See(NearestEnemyOf(Myself))
    Range(LastSeenBy(Myself),10)
    !HPPercentGT(Myself,50)
    !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
    !StateCheck(Myself,STATE_INVISIBLE)
THEN
    RESPONSE #100
        RunAwayFrom(NearestEnemyOf(Myself),10)
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),30)
END

