IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        FadeToColor([30.0],0)
        ActionOverride("AC#MALG1",EscapeAreaDestroy(0))
        Wait(2)
        LeaveAreaLUAPanic("ACIL36","",[337.1660],NE)
        LeaveAreaLUA("ACIL36","",[337.1660],NE)
        MultiPlayerSync()
        MoveViewPoint([337.1660],INSTANT)
        SmallWait(5)
        FadeFromColor([30.0],0)
        EndCutSceneMode()
END

