IF
    See(NearestEnemyOf(Myself))
    !Range(NearestEnemyOf(Myself),7)
THEN
    RESPONSE #100
        ForceSpell(NearestEnemyOf(Myself),PHASE_SPIDER_TELEPORT)  // SPWI994.SPL (Dimensionstor)
END

IF
    See(NearestEnemyOf(Myself))
    !Allegiance(Myself,GOODCUTOFF)
THEN
    RESPONSE #10
        ForceSpell(Player1,PHASE_SPIDER_TELEPORT)  // SPWI994.SPL (Dimensionstor)
    RESPONSE #10
        ForceSpell(Player2,PHASE_SPIDER_TELEPORT)  // SPWI994.SPL (Dimensionstor)
    RESPONSE #10
        ForceSpell(Player3,PHASE_SPIDER_TELEPORT)  // SPWI994.SPL (Dimensionstor)
    RESPONSE #10
        ForceSpell(Player4,PHASE_SPIDER_TELEPORT)  // SPWI994.SPL (Dimensionstor)
    RESPONSE #10
        ForceSpell(Player5,PHASE_SPIDER_TELEPORT)  // SPWI994.SPL (Dimensionstor)
    RESPONSE #10
        ForceSpell(Player6,PHASE_SPIDER_TELEPORT)  // SPWI994.SPL (Dimensionstor)
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

