IF
    See(NearestEnemyOf(Myself))
    Global("PITFEAR","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(NearestEnemyOf(Myself),DEMON_FEAR)  // SPIN890.SPL (Dämonenfurcht)
        SetGlobal("PITFEAR","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("DeathKnightFireball","LOCALS",0)
THEN
    RESPONSE #50
        ForceSpell(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Feuerball)
        SetGlobal("DeathKnightFireball","LOCALS",1)
    RESPONSE #50
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Magie zerstören)
        SetGlobal("DeathKnightFireball","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("DeathAttack","LOCALS",0)
THEN
    RESPONSE #20
        ForceSpell(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Feuerball)
        SetGlobal("DeathAttack","LOCALS",1)
    RESPONSE #20
        ForceSpell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (Symbol der Furcht)
        SetGlobal("DeathAttack","LOCALS",1)
    RESPONSE #60
        SetGlobal("DeathAttack","LOCALS",1)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    Global("DeathAttack","LOCALS",1)
THEN
    RESPONSE #50
        ForceSpell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (Symbol der Furcht)
        SetGlobal("DeathAttack","LOCALS",2)
    RESPONSE #50
        ForceSpell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (Symbol der Furcht)
        SetGlobal("DeathAttack","LOCALS",2)
END

IF
    See(NearestEnemyOf(Myself))
    Global("DeathAttack","LOCALS",2)
THEN
    RESPONSE #15
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (Symbol der Furcht)
    RESPONSE #15
        ReallyForceSpell(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Feuerball)
    RESPONSE #70
        Continue()
END

IF
    HPLT("AC#DUN02",15)  // Dunnabar Steinschulter
    Global("AttackPC","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("AttackPC","LOCALS",1)
END

IF
    AttackedBy("AC#DUN02",DEFAULT)  // Dunnabar Steinschulter
THEN
    RESPONSE #100
        RunAwayFrom(LastAttackerOf(Myself),6)
END

IF
    See(NearestEnemyOf(Myself))
    !Name("AC#DUN02",LastSeenBy(Myself))  // Dunnabar Steinschulter
    Global("AttackPC","LOCALS",0)
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),6)
    RESPONSE #100
        Continue()
END

IF
    See(SecondNearestEnemyOf(Myself))
    !Name("AC#DUN02",LastSeenBy(Myself))  // Dunnabar Steinschulter
    Global("AttackPC","LOCALS",0)
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy(Myself),6)
    RESPONSE #100
        Continue()
END

IF
    See(ThirdNearestEnemyOf(Myself))
    !Name("AC#DUN02",LastSeenBy(Myself))  // Dunnabar Steinschulter
    Global("AttackPC","LOCALS",0)
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy(Myself),6)
    RESPONSE #100
        Continue()
END

IF
    See([PC])
    Global("AttackPC","LOCALS",0)
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy(Myself),6)
END

IF
    See([PC])
    Global("AttackPC","LOCALS",1)
THEN
    RESPONSE #70
        AttackReevaluate(NearestEnemyOf(Myself),15)
    RESPONSE #20
        SetGlobal("PITFIRE","LOCALS",0)
END

IF
    !See([PC])
THEN
    RESPONSE #100
        MoveToObject([PC])
END

