/*
IF
    See([ANYONE])
    NumberOfTimesTalkedTo(0)
THEN
    RESPONSE #100
        StartDialogueNoSet(LastSeenBy(Myself))
END
*/

IF
    See(NearestEnemyOf(Myself))
    Global("PITFEAR","LOCALS",0)
THEN
    RESPONSE #100
        ForceSpell(NearestEnemyOf(Myself),DEMON_FEAR)  // SPIN890.SPL (Dämonenfurcht)
        SetGlobal("PITFEAR","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("DeathKnightFireball","LOCALS",0)
THEN
    RESPONSE #50
        ForceSpell(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Feuerball)
        SetGlobal("DeathKnightFireball","LOCALS",1)
    RESPONSE #50
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Magie zerstören)
        SetGlobal("DeathKnightFireball","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("DeathAttack","LOCALS",0)
THEN
    RESPONSE #20
        ForceSpell(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Feuerball)
        SetGlobal("DeathAttack","LOCALS",1)
    RESPONSE #20
        ForceSpell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (Symbol der Furcht)
        SetGlobal("DeathAttack","LOCALS",1)
    RESPONSE #60
        AttackReevaluate(LastSeenBy(Myself),15)
        SetGlobal("DeathAttack","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("DeathAttack","LOCALS",1)
THEN
    RESPONSE #50
        ForceSpell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (Symbol der Furcht)
        SetGlobal("DeathAttack","LOCALS",2)
    RESPONSE #50
        ForceSpell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (Symbol der Furcht)
        SetGlobal("DeathAttack","LOCALS",2)
END

IF
    See(NearestEnemyOf(Myself))
    Global("DeathAttack","LOCALS",2)
THEN
    RESPONSE #15
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (Symbol der Furcht)
    RESPONSE #15
        ReallyForceSpell(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Feuerball)
    RESPONSE #70
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
    HPLT("AC#DUN02",15)
    Global("AttackPC","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("AttackPC","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("AttackPC","LOCALS",0)
THEN
    RESPONSE #70
        AttackReevaluate(NearestEnemyOf(Myself),15)
    RESPONSE #20
        SetGlobal("PITFIRE","LOCALS",0)
END

IF
    See([PC])
    Global("AttackPC","LOCALS",1)
THEN
    RESPONSE #70
        AttackReevaluate(NearestEnemyOf(Myself),15)
    RESPONSE #20
        SetGlobal("PITFIRE","LOCALS",0)
END

