IF
    See(NearestEnemyOf(Myself))
    Range(NearestEnemyOf(Myself),15)
    Global("CastEarthquake","LOCALS",0)
    !GlobalTimerNotExpired("EarthquakeTimer","LOCALS")
    False()
THEN
    RESPONSE #100
        ForceSpellRES("AC#HAMG",NearestEnemyOf(Myself))  // Stampfende Kraft
        SetGlobal("CastEarthquake","LOCALS",1)
END

IF
    Global("CastEarthquake","LOCALS",1)
    See(NearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
        SetGlobal("CastEarthquake","LOCALS",0)
        SetGlobalTimer("EarthquakeTimer","LOCALS",ONE_TURN)
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),12)
END

IF
    ActionListEmpty()
    !See([ENEMY])
    !See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        RandomWalk()
END

