IF
    See(NearestEnemyOf(Myself))
    See(NearestMyGroupOfType)
    Global("prep","LOCALS",0)
THEN
    RESPONSE #100
        ReallyForceSpell(LastSeenBy(Myself),CLERIC_CHANT)  // SPPR203.SPL (Gesang)
        ReallyForceSpell(LastSeenBy(Myself),CLERIC_STRENGTH_OF_ONE)  // SPPR312.SPL (Vereinte Stärke)
        SetGlobal("prep","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    GlobalLT("Lighting","LOCALS",4)
    !GlobalTimerNotExpired("LightingTimer","LOCALS")
THEN
    RESPONSE #100
        ForceSpell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Blitzstrahl)
        SetGlobalTimer("LightingTimer","LOCALS",THREE_ROUNDS)
        IncrementGlobal("Lighting","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flammenschlag)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flammenschlag)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Mantel der Furcht)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Mantel der Furcht)
END

IF
    See(NearestEnemyOf(Myself))
    See(NearestMyGroupOfType)
    HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Massenheilung)
    HPPercentLT(Myself,80)
    OR(3)
        HPPercentLT(LastSeenBy(Myself),80)
        HPPercentLT(SecondNearestMyGroupOfType,80)
        HPPercentLT(ThirdNearestMyGroupOfType,80)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_MASS_CURE)  // SPPR514.SPL (Massenheilung)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
END

IF
    See(NearestEnemyOf(Myself))
    See(NearestMyGroupOfType)
    HPPercentLT(LastSeenBy(Myself),60)
    HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)  // SPPR401.SPL (Schwere Wunden heilen)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS)  // SPPR401.SPL (Schwere Wunden heilen)
END

IF
    See(NearestEnemyOf(Myself))
    See(NearestMyGroupOfType)
    HPPercentLT(LastSeenBy(Myself),10)
    HaveSpell(CLERIC_HEAL)  // SPPR607.SPL (Heilung)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_HEAL)  // SPPR607.SPL (Heilung)
END

IF
    See(NearestEnemyOf(Myself))
    !Range(LastSeenBy(Myself),4)
    HPPercentLT(Myself,60)
    HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)  // SPPR401.SPL (Schwere Wunden heilen)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CURE_SERIOUS_WOUNDS)  // SPPR401.SPL (Schwere Wunden heilen)
END

IF
    See(NearestEnemyOf(Myself))
    !Range(LastSeenBy(Myself),4)
    HPPercentLT(Myself,10)
    HaveSpell(CLERIC_HEAL)  // SPPR607.SPL (Heilung)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_HEAL)  // SPPR607.SPL (Heilung)
END

IF
    Heard([ANYONE],111)
THEN
    RESPONSE #100
        MoveToObject(NearestEnemyOf(Myself))
END

IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    !Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        Enemy()
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),30)
END

