IF
    Die()
THEN
    RESPONSE #100
        DisplayString(Myself,57749)  // Illusion gebannt
        ReallyForceSpellDead(Myself,ILLUSION_DEATH)  // SPIN835.SPL (No such index)
        Wait(1)
        DestroySelf()
END

IF
    HitBy([PC],SLASHING)
    HasItemEquipedReal("sw2h10",LastHitter)  // Carsomyr +5
THEN
    RESPONSE #100
        DisplayString(Myself,57749)  // Illusion gebannt
        SetSequence(SEQ_DIE)
        Wait(1)
        ReallyForceSpell(Myself,ILLUSION_DEATH)  // SPIN835.SPL (No such index)
        Wait(1)
        DestroySelf()
END

IF
    OR(6)
        SpellCast([PC],WIZARD_TRUE_SIGHT)  // SPWI609.SPL (Wahrer Blick)
        SpellCastPriest([PC],CLERIC_TRUE_SIGHT)  // SPPR505.SPL (Wahrer Blick)
        SpellCastInnateRES("SPCL232",[PC])  // Wahrer Blick
        SpellCastInnateRES("SPCL732",[PC])  // Wahrer Blick
        SpellCastInnate([PC],THIEF_DETECT_ILLUSION)  // SPIN805.SPL (No such index)
        SpellCast([PC],WIZARD_DETECT_ILLUSION)  // SPWI322.SPL (Illusion entdecken)
    See([PC])
THEN
    RESPONSE #100        
        DisplayString(Myself,57749)  // Illusion gebannt
        SetSequence(SEQ_DIE)
        Wait(1)
        ReallyForceSpell(Myself,ILLUSION_DEATH)  // SPIN835.SPL (No such index)
        Wait(1)
        DestroySelf()
END

IF
    See(NearestEnemyOf(Myself))
    Global("StartBreathTimer","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("StartBreathTimer","LOCALS",1)
        SetGlobalTimer("REDDRAGONBREATH","ACIL23",ONE_ROUND)
END

IF
    See(NearestEnemyOf(Myself))
    GlobalTimerExpired("REDDRAGONBREATH","ACIL23")
    Global("StartBreathTimer","LOCALS",1)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),RED_DRAGON_BREATH)  // SPIN894.SPL (Roter Drache: Odemwaffe)
        ReallyForceSpellRES("AC#IL23",LastSeenBy(Myself))  // Drachenodem
        SetGlobalTimer("REDDRAGONBREATH","ACIL23",THREE_ROUNDS)
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),5)
END

