IF
    See(NearestEnemyOf(Myself))
    !Range(NearestEnemyOf(Myself),6)
THEN
    RESPONSE #100
        EquipRanged()
        AttackReevaluate(NearestEnemyOf(Myself),12)
END

IF
    See(NearestEnemyOf(Myself))
    Range(NearestEnemyOf(Myself),6)
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(NearestEnemyOf(Myself),12)
END

IF
    See(NearestEnemyOf(Myself))
    !Range(NearestEnemyOf(Myself),6)
THEN
    RESPONSE #100
        SelectWeaponAbility(SLOT_WEAPON0,0)
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    !Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        Enemy()
END

IF
    See(NearestEnemyOf(Myself))
    Range(NearestEnemyOf(Myself),5)
    Delay(12)
THEN
    RESPONSE #40
        SelectWeaponAbility(SLOT_WEAPON0,0)
        RunAwayFrom(NearestEnemyOf(Myself),45)
        AttackReevaluate(NearestEnemyOf(Myself),15)
    RESPONSE #60
        SelectWeaponAbility(SLOT_WEAPON1,0)
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
    See(NearestEnemyOf(Myself))
    Delay(12)
THEN
    RESPONSE #40
        SelectWeaponAbility(SLOT_WEAPON0,0)
        AttackReevaluate(NearestEnemyOf(Myself),15)
    RESPONSE #60
        SelectWeaponAbility(SLOT_WEAPON1,0)
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
    See(NearestEnemyOf(Myself))
    ActionListEmpty()
THEN
    RESPONSE #40
        SelectWeaponAbility(SLOT_WEAPON0,0)
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

