IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        FadeToColor([30.0],0)
        Wait(2)
        LeaveAreaLUAPanic("ACIL64","",[1173.708],SW)
        LeaveAreaLUA("ACIL64","",[1173.708],SW)
        ActionOverride(Player2,LeaveAreaLUA("ACIL64","",[1154.677],SW))
        ActionOverride(Player3,LeaveAreaLUA("ACIL64","",[1208.714],SW))
        ActionOverride(Player4,LeaveAreaLUA("ACIL64","",[1238.725],SW))
        ActionOverride(Player5,LeaveAreaLUA("ACIL64","",[1129.663],SW))
        ActionOverride(Player6,LeaveAreaLUA("ACIL64","",[1110.631],SW))
        MultiPlayerSync()
        MoveViewPoint([1173.708],INSTANT)
        ActionOverride("AC#MITH5",SetNumTimesTalkedTo(3))
        FadeFromColor([30.0],0)
        Wait(3)
        EndCutSceneMode()
END

