IF
    Allegiance(Myself,ENEMY)
    Detect([PC])
    !See(LastSeenBy(Myself))
    HaveSpell(CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Unsichtbarkeit aufheben)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_INVISIBILITY_PURGE)  // SPPR309.SPL (Unsichtbarkeit aufheben)
END

IF
    See(NearestEnemyOf(Myself))
    OR(2)
        See("AC#IL26S")  // Riesenspinne
        See("AC#IL26K")  // Kleine Spinne
    HaveSpell(CLERIC_CHANT)  // SPPR203.SPL (Gesang)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_CHANT)  // SPPR203.SPL (Gesang)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_CHANT)  // SPPR203.SPL (Gesang)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Gesang)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_DEFENSIVE_HARMONY)  // SPPR406.SPL (Koordinierte Verteidigung)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_DEFENSIVE_HARMONY)  // SPPR406.SPL (Koordinierte Verteidigung)
END

IF
    See(SecondNearestEnemyOf(Myself))
    HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
    !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
    !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
END

IF
    HaveSpell(CLERIC_SILENCE_15_FOOT)  // SPPR211.SPL (Stille: 4,5 m Radius)
    OR(2)
        See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
        See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    Range(LastSeenBy(Myself),20)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)  // SPPR211.SPL (Stille: 4,5 m Radius)
END

IF
    See(SecondNearestEnemyOf(Myself))
    HaveSpell(CLERIC_COMMAND)  // SPPR102.SPL (Befehl)
THEN
    RESPONSE #50
        Spell(NearestEnemyOf(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Befehl)
    RESPONSE #50
        Spell(SecondNearestEnemyOf(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Befehl)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_COMMAND)  // SPPR102.SPL (Befehl)
THEN
    RESPONSE #50
        Spell(NearestEnemyOf(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Befehl)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Tote beleben)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Tote beleben)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Mantel der Furcht)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Mantel der Furcht)
END

IF
    See(NearestEnemyOf(Myself))
    See(NearestMyGroupOfType)
    HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Massenheilung)
    HPPercentLT(Myself,80)
    OR(3)
        HPPercentLT(LastSeenBy(Myself),80)
        HPPercentLT(SecondNearestMyGroupOfType,80)
        HPPercentLT(ThirdNearestMyGroupOfType,80)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_MASS_CURE)  // SPPR514.SPL (Massenheilung)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Personen festhalten)
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),6)
END

