IF
    Heard([ANYONE],111)
THEN
    RESPONSE #100
        MoveToObject(NearestEnemyOf(Myself))
END

IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    !Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        Enemy()
END

IF
    See(NearestEnemyOf(Myself))
    OR(5)
        See(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
        See(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
    !HasBounceEffects(LastSeenBy(Myself))
    GlobalLT("MelfsArrow","LOCALS",4)
    !GlobalTimerNotExpired("MelfsArrowTimer","LOCALS")
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melfs Säurepfeil)
        SetGlobalTimer("MelfsArrowTimer","LOCALS",THREE_ROUNDS)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("MelfsArrow","LOCALS",1)
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),30)
END

