IF
	Detect([PC])
	Dead("AC#ROTHB")
	OR(2)
	Global("RotheAttack","ACIL54",2)
        Global("RotheAttack","ACIL54",3)
THEN
	RESPONSE #100
                SetGlobal("RotheAttack","ACIL54",10)
		StartDialogueNoSet(LastSeenBy(Myself))
END

IF
	Detect([PC])
        See("AC#ROTHB")
	!Dead("AC#ROTHB")
	Allegiance("AC#ROTHB",ENEMY)
	Global("RotheAttack","ACIL54",2)
THEN
	RESPONSE #100
	        SetGlobal("RotheAttack","ACIL54",3)
		DisplayStringHead(Myself,@904)
END












