IF
    Dead("AC#BOAR2")  // Eber
    Global("AC#Boar","ACIL54",5)
THEN
    RESPONSE #100
        SetGlobal("AC#Boar","ACIL54",6)
        MoveToPointNoInterrupt([2617.1262])
END

IF
    Detect([PC])
    Dead("AC#BOAR2")  // Eber
    GlobalLT("AC#Boar","ACIL54",4)
    CombatCounter(0)
THEN
    RESPONSE #100
        SmallWait(15)
        SetGlobal("AC#Boar","ACIL54",4)
        StartDialogueNoSet(LastSeenBy(Myself))
END

IF
    Detect([PC])
    !Dead("AC#BOAR2")  // Eber
    Global("AC#Boar","ACIL54",0)
THEN
    RESPONSE #100
        SetGlobal("AC#Boar","ACIL54",1)
        StartDialogueNoSet(LastSeenBy(Myself))
END

IF
    !Dead("AC#BOAR2")  // Eber
    Global("AC#Boar","ACIL54",2)
THEN
    RESPONSE #100
        SetGlobal("AC#Boar","ACIL54",3)
        ActionOverride("AC#BOAR2",Attack("AC#ILDW3"))  // Thungal Aranthymvudd
END

IF
    HitBy("AC#BOAR2",CRUSHING)  // Eber
THEN
    RESPONSE #100
        Attack("AC#ILDW3")  // Thungal Aranthymvudd
END

