IF
    HitBy([PC],FIRE)
THEN
    RESPONSE #100
        ApplySpellRES("AC#ILHR",Myself)  // Unsichtbarkeit aufheben
        StartTimer(1,12)
        AttackReevaluate(NearestEnemyOf(Myself),12)
END

IF
    See(NearestEnemyOf(Myself))
    TimerExpired(1)
THEN
    RESPONSE #100
        StartTimer(1,6)
        DisplayString(Myself,19944)  // Im Schatten verstecken gelungen
        ApplySpell(Myself,WIZARD_INVISIBILITY)  // SPWI206.SPL (Unsichtbarkeit)
END

IF
    See(NearestEnemyOf(Myself))
    NumberOfTimesTalkedTo(0)
THEN
    RESPONSE #100
        SetNumTimesTalkedTo(1)
        StartTimer(1,6)
END

IF
    See(NearestEnemyOf(Myself))
    BecameVisible()
    Global("Bark","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("Bark","LOCALS",1)
        ApplySpell(Myself,CLERIC_CLOAK_OF_FEAR)  // SPPR416.SPL (Mantel der Furcht)
END

IF
    Heard([ANYONE],111)
THEN
    RESPONSE #100
        MoveToObject(NearestEnemyOf(Myself))
END

IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    !Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        Enemy()
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(NearestEnemyOf(Myself),6)
END

