IF
    Detect([PC])
    Dead("AC#ROTHB")  // Tiefenrothé
    CombatCounter(0)
    OR(2)
        Global("RotheAttack","ACIL54",2)
        Global("RotheAttack","ACIL54",3)
THEN
    RESPONSE #100
        SetGlobal("RotheAttack","ACIL54",10)
        StartDialogueNoSet(LastSeenBy(Myself))
END

IF
    Detect([PC])
    See("AC#ROTHB")  // Tiefenrothé
    !Dead("AC#ROTHB")  // Tiefenrothé
    Allegiance("AC#ROTHB",ENEMY)  // Tiefenrothé
    Global("RotheAttack","ACIL54",2)
THEN
    RESPONSE #100
        SetGlobal("RotheAttack","ACIL54",3)
        DisplayStringHead(Myself,104742)  // Borug? Borug! Hilfe, er greift mich an!
END

