IF
    See(NearestEnemyOf(Myself))
    OR(2)
        StateCheck(Myself,STATE_INVISIBLE)
        StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(WorstAC([PC]),12)
END

IF
    See(NearestEnemyOf(Myself))
    Delay(18)
    GlobalLT("Cloudkill","LOCALS",2)
    !GlobalTimerNotExpired("CloudkillTimer","LOCALS")
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        ForceSpell(NearestEnemyOf(Myself),WIZARD_CLOUDKILL)  // SPWI502.SPL (Todeswolke)
        SetGlobalTimer("CloudkillTimer","LOCALS",ONE_TURN)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("Cloudkill","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    !StateCheck(Myself,STATE_INVISIBLE)
    !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
    HasItem("POTN10",Myself)  // Unsichtbarkeitstrank
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
THEN
    RESPONSE #100
        UseItem("POTN10",Myself)  // Unsichtbarkeitstrank
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
END

IF
    See(NearestEnemyOf(Myself))
    !Range(NearestEnemyOf(Myself),5)
THEN
    RESPONSE #100
        EquipRanged()
        AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
    See(NearestEnemyOf(Myself))
    Range(NearestEnemyOf(Myself),5)
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
    AttackedBy([ANYONE],DEFAULT)
THEN
    RESPONSE #100
        AttackReevaluate(LastAttackerOf(Myself),30)
END

