IF
	Die()
THEN
	RESPONSE #100
		ReallyForceSpellDead(Myself,VAMPIRE_GAS_FORM_CHANGE)  // SPIN964.SPL (No such index)
END

IF
	LevelLT(Player1,12)
	!DifficultyGT(NORMAL)
THEN
	RESPONSE #100
		SetGlobal("DeactivateVamps","ACIL28",1)
		DestroySelf()
END

IF
	See(NearestEnemyOf(Myself))
	Global("blast","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("blast","LOCALS",1)
		ForceSpell(LastSeenBy(Myself),BRAIN_PSIONIC_BLAST)  // SPIN834.SPL (Psi-Schlag)
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Shout(89)
		Enemy()
END

IF
	HitBy([GOODCUTOFF],CRUSHING)
THEN
	RESPONSE #100
		Shout(89)
		Continue()
END

IF
	OR(5)
		AttackedBy([PC],DEFAULT)
		AttackedBy([FAMILIAR],DEFAULT)
		AttackedBy([ALLY],DEFAULT)
		AttackedBy([CONTROLLED],DEFAULT)
		AttackedBy([CHARMED],DEFAULT)
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
THEN
	RESPONSE #100
		Shout(89)
		Continue()
END

IF
	Heard([ANYONE],89)
	Allegiance(Myself,NEUTRAL)
	!Class(Myself,INNOCENT)
THEN
	RESPONSE #100
		Enemy()
		MoveToObject(LastHeardBy(Myself))
END

IF
	Heard([ANYONE],89)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Heard([ANYONE],89)
	!Class(Myself,INNOCENT)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
		Continue()
END

