IF
    HitBy([GOODCUTOFF],CRUSHING)
THEN
    RESPONSE #100
        Shout(151)
        Continue()
END

IF
    See([GOODCUTOFF])
    Allegiance(Myself,ENEMY)
    ActionListEmpty()
THEN
    RESPONSE #100
        Shout(151)
        Continue()
END

IF
    HPPercentLT(Myself,30)
    HPGT(Myself,1)
    !StateCheck(Myself,STATE_REALLY_DEAD)
    Global("Whined","LOCALS",0)
    See(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #50
        SetGlobal("Whined","LOCALS",1)
        Shout(153)
    RESPONSE #50
        SetGlobal("Whined","LOCALS",1)
        Shout(153)
    RESPONSE #50
        SetGlobal("Whined","LOCALS",1)
        Shout(153)
    RESPONSE #50
        SetGlobal("Whined","LOCALS",1)
        Shout(153)
END

