IF
	InMyArea(Player1)
	See(Player1)
	!See([ENEMY])
	Global("ACIL81_Way_Open","ACIL81",1)
	Global("AC#ChoseMarilith","ACIL81",2)
	Global("MarilithGoodbye","ACIL81",0)
THEN
	RESPONSE #100
	        SetGlobal("MarilithGoodbye","ACIL81",1)
		StartDialogNoSet(Player1)
END

IF
	Delay(2)
	InMyArea(Player1)
	!Range(Player1,15)
	!See([ENEMY])
	Global("AC#ChoseMarilith","ACIL81",2)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	See("AC#DEVA1")
        !Dead("AC#DEVA1")
	Global("AC#ChoseNone","ACIL81",1)
THEN
	RESPONSE #100
                 AttackReevaluate("AC#DEVA1",30)
END

IF
        Dead("AC#DEVA1")
	Global("AC#ChoseMarilith","ACIL81",1)
THEN
	RESPONSE #100
	        ChangeEnemyAlly(Myself,GOODBUTBLUE)
	        SetGlobal("Prep","LOCALS",1)
                SetGlobal("AC#ChoseMarilith","ACIL81",2)
END

IF
	See("AC#DEVA1")
        !Dead("AC#DEVA1")
	Global("AC#ChoseMarilith","ACIL81",1)
THEN
	RESPONSE #100
                 AttackReevaluate("AC#DEVA1",30)
END

IF
	Dead("AC#DEVA1")
	Global("AC#ChoseNone","ACIL81",1)
THEN
	RESPONSE #100
		SetGlobal("AC#ChoseNone","ACIL81",2)
		CreateVisualEffectObject("SPDIMNDR",Myself)
		Wait(1)
	        DestroySelf()
END

IF
	See(NearestEnemyOf(Myself))
	Global("Prep","LOCALS",0)
THEN
	RESPONSE #100
		ApplySpell(Myself,CLERIC_ANIMATE_DEAD)  // SPPR301.SPL (Tote beleben)
		ForceSpell(NearestEnemyOf(Myself),WIZARD_CLOUDKILL)  // SPWI502.SPL (Todeswolke)
		SetGlobal("Prep","LOCALS",1)
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	!Allegiance(Myself,ENEMY)
	!Global("AC#ChoseMarilith","ACIL81",2)
THEN
	RESPONSE #100
		Enemy()
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	AttackedBy([ANYONE],DEFAULT)
	!Global("AC#ChoseMarilith","ACIL81",2)
THEN
	RESPONSE #100
		Attack(LastAttackerOf(Myself))
END
