IF
    HasItem("AC#NEO2",Myself)  // No such index
    OR(2)
        HPLT(Myself,15)
        Die()
THEN
    RESPONSE #100
        DestroyItem("AC#NEO2")  // No such index
END

IF
    Global("Stronger","LOCALS",0)
    LevelPartyGT(12)
THEN
    RESPONSE #100
        ApplySpellRES("AC#ILX1",Myself)  // No such index
        SetGlobal("Stronger","LOCALS",1)
END

IF
    Global("Stronger","LOCALS",1)
    LevelPartyGT(15)
THEN
    RESPONSE #100
        ApplySpellRES("AC#ILX1",Myself)  // No such index
        SetGlobal("Stronger","LOCALS",2)
END

IF
    See(NearestEnemyOf(Myself))
    Global("bd_combat","locals",0)
THEN
    RESPONSE #100
        SetGlobal("bd_combat","locals",1)
        AnkhegEmerge()
        AttackReevaluate(NearestEnemyOf(Myself),6)
END

IF
    See(SixthNearestEnemyOf(Myself))
THEN
    RESPONSE #50
        AnkhegHide()
        MoveToObject(LastSeenBy(Myself))
        AttackReevaluate(LastSeenBy(Myself),6)
        Continue()
    RESPONSE #100
        Continue()
END

IF
    HitBy([ANYONE],CRUSHING)
THEN
    RESPONSE #100
        Continue()
    RESPONSE #50
        AnkhegHide()
        RunAwayFrom(NearestEnemyOf(Myself),12)
        Continue()
END

IF
    OR(2)
        Difficulty(EASIEST)
        Difficulty(EASY)
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("bd_cast","locals")
    Global("Neothelid_Breath","LOCALS",0)
THEN
    RESPONSE #100
        AnkhegEmerge()
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        SetGlobal("Neothelid_Breath","LOCALS",1)
        ForceSpellRES("AC#NEOB",LastSeenBy(Myself))  // Enzymatischer Odem
        AttackOneRound(LastSeenBy(Myself))
END

IF
    OR(2)
        DifficultyGT(HARD)
        LevelPartyGT(15)
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("Neothelid_Breath_Timer","LOCALS")
    !GlobalTimerNotExpired("bd_cast","locals")
    GlobalLT("Neothelid_Breath","LOCALS",3)
THEN
    RESPONSE #100
        AnkhegEmerge()
        SetGlobalTimer("Neothelid_Breath_Timer","LOCALS",TWO_ROUNDS)
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        IncrementGlobal("Neothelid_Breath","LOCALS",1)
        ForceSpellRES("AC#NEOB",LastSeenBy(Myself))  // Enzymatischer Odem
        AttackOneRound(LastSeenBy(Myself))
END

IF
    Difficulty(HARD)
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("Neothelid_Breath_Timer","LOCALS")
    !GlobalTimerNotExpired("bd_cast","locals")
    GlobalLT("Neothelid_Breath","LOCALS",3)
THEN
    RESPONSE #100
        AnkhegEmerge()
        SetGlobalTimer("Neothelid_Breath_Timer","LOCALS",FOUR_ROUNDS)
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        IncrementGlobal("Neothelid_Breath","LOCALS",1)
        ForceSpellRES("AC#NEOB",LastSeenBy(Myself))  // Enzymatischer Odem
        AttackOneRound(LastSeenBy(Myself))
END

IF
    Difficulty(NORMAL)
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("Neothelid_Breath_Timer","LOCALS")
    !GlobalTimerNotExpired("bd_cast","locals")
    GlobalLT("Neothelid_Breath","LOCALS",3)
THEN
    RESPONSE #100
        AnkhegEmerge()
        SetGlobalTimer("Neothelid_Breath_Timer","LOCALS",FIVE_ROUNDS)
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        IncrementGlobal("Neothelid_Breath","LOCALS",1)
        ForceSpellRES("AC#NEOB",LastSeenBy(Myself))  // Enzymatischer Odem
        AttackOneRound(LastSeenBy(Myself))
END

IF
    !GlobalTimerNotExpired("bd_cast","locals")
    HPPercentLT(Myself,80)
    DifficultyGT(EASY)
    !GlobalTimerNotExpired("PSIONIC_TASTE_LINK","locals")
    See(NearestEnemyOf(Myself))
    !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        AnkhegEmerge()
        SetGlobalTimer("PSIONIC_TASTE_LINK","locals",TWO_ROUNDS)
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        SpellNoDecRES("AC#NEO1",Myself)  // Essenzraub
        AnkhegHide()
        RunAwayFrom(NearestEnemyOf(Myself),6)
    RESPONSE #35
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("bd_cast","locals")
    DifficultyGT(EASY)
    !GlobalTimerNotExpired("PSIONIC_DOMINATION","locals")
THEN
    RESPONSE #100
        AnkhegEmerge()
        SetGlobalTimer("PSIONIC_DOMINATION","locals",FIVE_ROUNDS)
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        SpellNoDec(LastSeenBy,PSIONIC_DOMINATION)  // SPIN910.SPL (Beherrschung)
END

IF
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("bd_cast","locals")
    !GlobalTimerNotExpired("PSIONIC_DOMINATION","locals")
THEN
    RESPONSE #100
        SetGlobalTimer("PSIONIC_DOMINATION","locals",TWO_ROUNDS)
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        SpellNoDec(LastSeenBy,PSIONIC_DOMINATION)  // SPIN910.SPL (Beherrschung)
    RESPONSE #50
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("bd_cast","locals")
    !GlobalTimerNotExpired("PSIONIC_TELEKINESIS","locals")
    GlobalLT("bd_telekinetic_sword","myarea",6)
THEN
    RESPONSE #100
        IncrementGlobal("bd_telekinetic_sword","myarea",1)
        SetGlobalTimer("PSIONIC_TELEKINESIS","locals",FIVE_ROUNDS)
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        SpellNoDecRES("AC#NEO2",LastSeenBy)  // Telekinese
        AttackOneRound(LastSeenBy(Myself))
    RESPONSE #40
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("bd_cast","locals")
THEN
    RESPONSE #100
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        SpellNoDec(LastSeenBy,PSIONIC_EGOWHIP)  // SPIN909.SPL (Egopeitsche)
        AttackOneRound(LastSeenBy(Myself))
    RESPONSE #50
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("bd_cast","locals")
THEN
    RESPONSE #100
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        SpellNoDecRES("AC#NEO3",LastSeenBy)  // Leib beherrschen
        AttackOneRound(LastSeenBy(Myself))
    RESPONSE #50
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("bd_cast","locals")
THEN
    RESPONSE #100
        SetGlobalTimer("bd_cast","locals",ONE_ROUND)
        SpellNoDecRES("AC#NEO4",LastSeenBy)  // Geistige Verwirrung
        AttackOneRound(LastSeenBy(Myself))
    RESPONSE #50
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy,6)
END

IF
    Global("bd_combat","locals",1)
    !Detect(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        RandomWalkContinuous()
END

