IF
    Global("AC#Ellhimar_Cernd","GLOBAL",4)
    See([PC])
THEN
    RESPONSE #100
        SetGlobal("AC#Ellhimar_Cernd","GLOBAL",5)
END

IF
    NumberOfTimesTalkedTo(0)
    Global("AC#Ellhimar_Cernd","GLOBAL",3)
THEN
    RESPONSE #100
        SetNumTimesTalkedTo(1)
END

IF
    AreaCheck("ACIL50")
    Global("AC#IL_NEW_Borthun","GLOBAL",1)
THEN
    RESPONSE #100
        EscapeAreaDestroy(6)
END

IF
    Range([PC],10)
    Global("AC#IL_NEW_Cernd","GLOBAL",2)
    See([PC])
THEN
    RESPONSE #100
        StartDialogueNoSet([PC])
END

