IF
    Global("AC#IL_ACIL20Portal","GLOBAL",10)
THEN
    RESPONSE #100
        EscapeArea()
END

IF
    See([PC])
    Global("AC#IL_ACIL20Portal","GLOBAL",2)
THEN
    RESPONSE #100
        StartDialogueNoSet([PC])
END

IF
    Global("AC#IL_ACIL20Portal","GLOBAL",5)
THEN
    RESPONSE #100
        Wait(1)
        StartDialogueNoSet([PC])
END

IF
    Global("AC#IL_ACIL20Portal","GLOBAL",7)
    Global("GithruneCutscene","ACIL20",10)
THEN
    RESPONSE #100
        ApplySpell(Player1,FLASHY_1)  // SPIN797.SPL (No such index)
        VerbalConstant(Player1,DYING)
        ActionOverride(Player1,PlayDead(18))
        Wait(2)
        StartDialogueNoSet([PC])
END

