IF
	Dead("AC#WD#O1") // orc leader
THEN
	RESPONSE #100
		EscapeArea()
END

IF
	OnCreation()
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
END

IF
	!Allegiance(Myself,ENEMY)
	Global("OrcsFree","ACIL14",20)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Global("OrcsFree","ACIL14",10)
THEN
	RESPONSE #100
		EscapeArea()
END

IF
       HasItem("AROW04",Myself)
       Global("Firearrows","ACIL14",10)
       Global("Fightwithfire","LOCALS",0)
THEN
	RESPONSE #100
		DestroyItem("AROW04")
		EquipRanged()
		SetGlobal("Fightwithfire","LOCALS",1)
END

IF
       HasItem("AROW08",Myself)
       Global("Acidarrows","ACIL14",10)
       Global("Fightwithacid","LOCALS",0)
THEN
	RESPONSE #100
		DestroyItem("AROW08")
		EquipRanged()
		SetGlobal("Fightwithacid","LOCALS",1)
END

IF
	Delay(2)
	InMyArea("AC#WD#O1")
	!Range("AC#WD#O1",15)
	!See([ENEMY])
	Global("OrcsFree","ACIL14",2)
	Global("Allied","LOCALS",1)
THEN
	RESPONSE #100
		MoveToObject("AC#WD#O1")
END

IF
	See([ENEMY.0.TROLL])
	Allegiance(Myself,GOODBUTBLUE)
THEN
	RESPONSE #100
	        EquipRanged()
		AttackReevaluate([ENEMY.0.TROLL],30)
END

IF
	Global("OrcsFree","ACIL14",2)
        Global("Allied","LOCALS",0)
THEN
	RESPONSE #100
		ChangeEnemyAlly(Myself,GOODBUTBLUE)
		SetGlobal("Allied","LOCALS",1)
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	!Allegiance(Myself,ENEMY)
	!Global("OrcsFree","ACIL14",2)
THEN
	RESPONSE #100
		Enemy()
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,GOODBUTBLUE)
	Global("OrcsFree","ACIL14",2)
        !See([ENEMY])
THEN
	RESPONSE #100
	        SetGlobal("OrcsFree","ACIL14",20)
		Enemy()
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),30)
END


