IF
    HPPercentLT("AC#CHARV",50)  // Charvekannathor
    Global("MoveToHeal","ACIL47",0)
    !Global("HealWorkaround","ACIL47",3)
THEN
    RESPONSE #100
        SetGlobal("MoveToHeal","ACIL47",1)
        ActionOverride("AC#CHARV",ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET))  // SPIN695.SPL (Flügelschlag)
        ActionOverride("AC#CHARV",MoveToPointNoInterrupt([609.661]))
END

IF
    Global("Deactivate_Ruby01","ACIL47",1)
    Global("Deactivate_Ruby02","ACIL47",1)
    Global("Deactivate_Ruby03","ACIL47",1)
    Global("MoveToHeal","ACIL47",0)
THEN
    RESPONSE #100
        SetGlobal("MoveToHeal","ACIL47",3)
END

IF
    !Contains("AC#IL47R","Ruby01")  // Riesiger Rubin
    Global("Deactivate_Ruby01","ACIL47",0)
THEN
    RESPONSE #100
        SetGlobal("Deactivate_Ruby01","ACIL47",1)
        ContainerEnable("Ruby01",FALSE)
        AmbientActivate("Ruby_bam01",FALSE)
END

IF
    !Contains("AC#IL47R","Ruby02")  // Riesiger Rubin
    Global("Deactivate_Ruby02","ACIL47",0)
THEN
    RESPONSE #100
        SetGlobal("Deactivate_Ruby02","ACIL47",1)
        ContainerEnable("Ruby02",FALSE)
        AmbientActivate("Ruby_bam02",FALSE)
END

IF
    !Contains("AC#IL47R","Ruby03")  // Riesiger Rubin
    Global("Deactivate_Ruby03","ACIL47",0)
THEN
    RESPONSE #100
        SetGlobal("Deactivate_Ruby03","ACIL47",1)
        ContainerEnable("Ruby03",FALSE)
        AmbientActivate("Ruby_bam03",FALSE)
END

/*
IF
	GlobalGT("AC#ShanatarScepters","GLOBAL",0)
	Global("CreateScepter","ACIL47",0)
THEN
	RESPONSE #100
		SetGlobal("CreateScepter","ACIL47",1)
                ActionOverride("Drakkalor_scepter",CreateItem("AC#ZEPDR",0,0,0))
END
*/

IF
	OR(2)
		Dead("AC#CHARV")
		Dead("AC#CHARR")
	Global("AC#IL_CharvDead","GLOBAL",0) 
THEN
	RESPONSE #100
		SetGlobal("AC#IL_CharvDead","GLOBAL",1)  
		AddJournalEntry(@51101,QUEST)
END

IF
	OR(2)
	Dead("AC#CHARV")
	Dead("AC#CHARR")
	Global("DeactivateRest","ACIL47",0) 
THEN
	RESPONSE #100
		SetGlobal("DeactivateRest","ACIL47",1)  
		SetRestEncounterProbabilityDay(0)
		SetRestEncounterProbabilityNight(0)
END