IF
    Global("CreateDeadBeholder","ACIL29",0)
    Dead("AC#ILBH1")  // Betrachter
THEN
    RESPONSE #100
        SetGlobal("CreateDeadBeholder","ACIL29",1)
        ActionOverride("Eyestalk",CreateItem("AC#EYEBE",0,0,0))  // Augenstiel eines Betrachters
        CreateCreature("AC#ILBHD",[296.1361],S)  // Betrachter
END

IF
	Global("AC#_VaxallDead","ACIL29",0)
	Dead("hlvaxal")
THEN
	RESPONSE #100
		SetGlobal("AC#_VaxallDead","ACIL29",1)
		ActionOverride("Quest_Chest",CreateItem("AC#VAX29",0,0,0)) // Spitzbubenstein
END

IF
	Global("Has_Eyestalk","ACIL29",0)
	PartyHasItem("ac#eyebe")
THEN
	RESPONSE #100
	         Wait(1)
		SetGlobal("Has_Eyestalk","ACIL29",1)
		//EraseJournalEntry(@64202)
		//EraseJournalEntry(@64203)
	    AddJournalEntry(@64204,QUEST)
END

