IF
	InMyArea(Player1)
	Global("MalphasGithCutscene#1","ACIL36",0) 
THEN
	RESPONSE #100
		FadeToColor([0.0],0)
		SetGlobal("MalphasGithCutscene#1","ACIL36",1)  
		StartCutSceneMode()
		StartCutScene("AC#GCT1")
END

IF
	Global("DisableAnimations","ACIL36",0)
THEN
	RESPONSE #100
	SetGlobal("DisableAnimations","ACIL36",1)
    AmbientActivate("Stone_broken",FALSE)
	AddJournalEntry(@62048,QUEST)
END

IF
    InMyArea(Player1)
    Global("AC#_IL_Area_37","GLOBAL",1)
THEN
    RESPONSE #100
        SetGlobal("AC#_IL_Area_37","GLOBAL",0)
        DisplayString(Myself,@7101)
        AdvanceTime(TWENTY_HOURS)
END

IF
    Global("CreateWaterWeird","ACIL36",0)
THEN
    RESPONSE #100
        SetGlobal("CreateWaterWeird","ACIL36",1)
        CreateCreatureImpassableAllowOverlap("AC#WATW2",[646.1002],S)
        CreateCreatureImpassableAllowOverlap("AC#WATW2",[972.1388],NW)
        CreateCreatureImpassableAllowOverlap("AC#WATW2",[1448.852],NW)
        CreateCreatureImpassableAllowOverlap("AC#WATW2",[1153.655],S)
        CreateCreatureImpassableAllowOverlap("AC#WATW2",[1965.1324],NW)
END

IF
	Global("GolemDoor","ACIL36",1)
        OpenState("DOOR01",FALSE)
THEN
	RESPONSE #100
                Wait(1)
                OpenDoor("DOOR01")
                AmbientActivate("Stone_closed",FALSE)
                PlaySound("EFF_P92")
                AmbientActivate("Stone_broken",TRUE)
		SetGlobal("GolemDoor","ACIL36",2)
END

