IF
    InMyArea(Player1)
    Global("AC#_IL_Area_45","GLOBAL",0)
THEN
    RESPONSE #100
        SetGlobal("AC#_IL_Area_45","GLOBAL",1)
        DisplayString(Myself,@7100)
        AdvanceTime(TWENTYONE_HOURS)
END

IF
	OR(2)
		Dead("AC#CHARV")
		Dead("AC#CHARR")
	Global("AC#IL_CharvDead","GLOBAL",0) 
THEN
	RESPONSE #100
		SetGlobal("AC#IL_CharvDead","GLOBAL",1)  
		AddJournalEntry(@51101,QUEST)
END

/*
IF
	Global("EnteredArea","ACIL45",0)
THEN
	RESPONSE #100
		SetGlobal("EnteredArea","ACIL45",1)
		AddJournalEntry(@45000,INFO)
END
*/
/*
Rest in the city of greed

IF
	Global("Theft","ACIL45",1)
THEN
	RESPONSE #100
                 Wait(6)
                 SetGlobal("Theft","ACIL45",0)
END

IF
	PartyRested()
	Global("Theft","ACIL45",0)
THEN
	RESPONSE #100
                 TakePartyGold(250)
                 SetGlobal("Theft","ACIL45",1)
END
*/