IF
	Global("DisableAnimations","ACIL80",0)
THEN
	RESPONSE #100
		SetGlobal("DisableAnimations","ACIL80",1)
		AmbientActivate("Portala",TRUE)
		SoundActivate("Amb_portal_a",TRUE)
		TriggerActivation("Travel_A_B",TRUE)
		AmbientActivate("Portalb",FALSE)
		SoundActivate("Amb_portal_b",FALSE)
		TriggerActivation("Travel_B_C",FALSE)
		AmbientActivate("Portalc",TRUE)
		SoundActivate("Amb_portal_c",TRUE)
		TriggerActivation("Travel_C_A",TRUE)
		AmbientActivate("Portald",FALSE)
		SoundActivate("Amb_portal_d",FALSE)
		TriggerActivation("Travel_d_e",FALSE)
		AmbientActivate("Portale",TRUE)
		SoundActivate("Amb_portal_e",TRUE)
		TriggerActivation("Travel_E_D",TRUE)
		SpawnPtDeactivate("Skeletonarmy01")
		SpawnPtDeactivate("Skeletonarmy02")
		SpawnPtDeactivate("Skeletonwarriors")
END

IF
	Global("AC#ACIL80CutScene2","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("AC#ACIL80CutScene2","GLOBAL",2)
END

IF
    Global("AC#MithbarakazCurse","GLOBAL",0)
    Global("AC#JourKalzaDead","GLOBAL",0)
THEN
    RESPONSE #100
        SetGlobal("AC#JourKalzaDead","GLOBAL",1)
        AddJournalEntry(@79701,QUEST_DONE) 
END

IF
	OpenState("DOOR01",TRUE)
	Global("SpawnXP","ACIL80",0)
THEN
	RESPONSE #100
		SetGlobal("SpawnXP","ACIL80",1)
		AddExperienceParty(10000)
		SpawnPtActivate("Skeletonarmy01")
		SpawnPtActivate("Skeletonarmy02")
		SpawnPtActivate("Skeletonwarriors")
END

IF
	OR(2)
		DifficultyGT(NORMAL)
		LevelGT(Player1,10)
	GlobalGT("SpawnXP","ACIL80",0)
	Global("SpawnSkelMage","ACIL80",0)
THEN
	RESPONSE #100
		SetGlobal("SpawnSkelMage","ACIL80",1)
		CreateCreature("AC#80SK4",[1618.993],3)  // Skelett-Magier
END

IF
    Global("AC#IL_TiamatKey","GLOBAL",0)
    PartyHasItem("AC#KY801")
    PartyHasItem("AC#KY802")
    PartyHasItem("AC#KY803")
    PartyHasItem("AC#KY804")
    PartyHasItem("AC#KY805")
THEN
    RESPONSE #100
        TakePartyItem("AC#KY802")
        TakePartyItem("AC#KY803")
        TakePartyItem("AC#KY804")
        TakePartyItem("AC#KY805")
        TakeItemReplace("AC#KEY80","AC#KY801",Player1)
		CreateVisualEffectObject("ICMAGICH",Player1)
		DisplayStringHead(Player1,@7800)
		SetGlobal("AC#IL_TiamatKey","GLOBAL",1)
END

