IF
    Global("AC#EnteredSpiderstalkings","GLOBAL",0)
THEN
    RESPONSE #100
        SetGlobal("AC#EnteredSpiderstalkings","GLOBAL",1)
        TriggerActivation("Trap_Drow01",FALSE)
        SpawnPtDeactivate("MyrlocharSpawn01")
END

IF
    Global("AC#Door25","ACIL25",2)
    Global("Deactivate","ACIL25",0)
THEN
    RESPONSE #100
        SetGlobal("Deactivate","ACIL25",1)
        TriggerActivation("Doorhead",FALSE)
        OpenDoor("DOOR01")
END

IF
    Global("JorunalUpdate","ACIL25",0)
THEN
    RESPONSE #100
    AddJournalEntry(@62023,QUEST_DONE)
        SetGlobal("JorunalUpdate","ACIL25",1)
END

IF
    Global("AC#IL25_MithrilGone","GLOBAL",0)
    Contains("AC#MITH1","Mithril_vein")
THEN
    RESPONSE #100
    ActionOverride("Mithril_vein",DestroyItem("AC#MITH1"))
        SetGlobal("AC#IL25_MithrilGone","GLOBAL",1)
END

IF
    Global("AC#IL25_RubiesGone","GLOBAL",0)
THEN
    RESPONSE #100
        ActionOverride("Gems01",DestroyItem("ac#ruby1"))
        ActionOverride("Gems02",DestroyItem("ac#ruby1"))
        SetGlobal("AC#IL25_RubiesGone","GLOBAL",1)
END

IF
    DifficultyGT(EASY)
    Global("CreateMoreDriders","ACIL25",1)
THEN
    RESPONSE #100
        SetGlobal("CreateMoreDriders","ACIL25",2)
        CreateCreature("AC#ILDDF",[939.540],S)  // Spinnenelf
        CreateCreature("AC#ILDDF",[1777.920],NEE)  // Spinnenelf
        CreateCreature("AC#ILDDF",[1530.425],NWW)  // Spinnenelf
END

IF
    Global("AC#25_LolthPriestess","GLOBAL",1)
THEN
    RESPONSE #100
        SetGlobal("AC#25_LolthPriestess","GLOBAL",2)
        TriggerActivation("Trap_Drow01",TRUE)
        SpawnPtActivate("MyrlocharSpawn01")
        CreateCreature("AC#DROW6",[2428.339],S)  // Zilna
        CreateCreature("AC#DROW7",[2309.280],NWW)  // Drow
        CreateCreature("AC#DROW8",[2535.285],SEE)  // Drow
        CreateCreature("AC#DROW7",[1112.826],NNE)  // Drow
        CreateCreature("AC#DROW7",[2206.406],NWW)  // Drow
END

IF
    PartyHasItem("AC#ILMBJ")  // Mith Baraks Notizen
    Global("Spawn_Githyanki","ACIL25",0)
THEN
    RESPONSE #100
        SetGlobal("Spawn_Githyanki","ACIL25",1)
        CreateCreature("AC#25GI1",[3153.598],N)  // Githyanki
        CreateCreature("AC#25GI2",[3116.682],N)  // Githyanki
        CreateCreature("AC#25GI2",[3204.694],N)  // Githyanki
        CreateCreature("AC#25GI2",[3130.762],N)  // Githyanki
        CreateCreature("AC#25GI2",[3224.740],N)  // Githyanki
END

