// Silverrealms animation files

//_____________________________________________________________________________________________________
// DRACOLICH animation
/*
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x1200 slotMax = 0x1300 RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END

  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#DRACOLICH~ UNLESS ~AC#DRACOLICH~
  CLEAR_IDS_MAP

  COPY ~%MOD_FOLDER%/animations/dracolich_ini/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/dracolich~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  COPY ~%MOD_FOLDER%/animations/intellect_devourer/intellect_devourer_sounds~ ~override~
  END
*/

//_____________________________________________________________________________________________________
// Doomspawn animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7f15 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% DOOMSPAWN_ACIFER~ UNLESS ~DOOMSPAWN_ACIFER~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Doomspawn/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Doomspawn~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  COPY ~%MOD_FOLDER%/animations/Doomspawn/Doomspawn-sounds~ ~override~
  END

//_____________________________________________________________________________________________________
// Dragonwraith animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7f15 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% DRAGONWRAITH_ACIFER~ UNLESS ~DRAGONWRAITH_ACIFER~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Dragonwraith/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Dragonwraith~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  COPY ~%MOD_FOLDER%/animations/Dragonwraith/Dragonwraith-sounds~ ~override~
  END

// intellect_devourer animation courtesy of Artemius
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% C0_INTELLECT_DEVOURER~ UNLESS ~C0_INTELLECT_DEVOURER~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/intellect_devourer/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/intellect_devourer~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
      COPY ~%MOD_FOLDER%/animations/intellect_devourer/intellect_devourer_sounds~ ~override~
  END

// invisble creature large animation
 LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7d00 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% INVISIBLE_LARGE_ACIFER~ UNLESS ~INVISIBLE_LARGE_ACIFER~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/invisible_creature_large/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/invisible_creature_large~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END

// small water elemental animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#ELEMENTAL_WATER_SMALL~ UNLESS ~AC#ELEMENTAL_WATER_SMALL~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/water_elemental_small_EE/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/water_elemental_small_EE~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
//_____________________________________________________________________________________________________
// Malphas animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7f15 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% MALPHAS_ACIFER~ UNLESS ~MALPHAS_ACIFER~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Malphas/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Malphas~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  COPY ~%MOD_FOLDER%/animations/Malphas/Malphas-sounds~ ~override~
  END

//_____________________________________________________________________________________________________
// Hezrou animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7f15 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% HEZROU_ACIFER~ UNLESS ~HEZROU_ACIFER~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Hezrou/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Hezrou~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  COPY ~%MOD_FOLDER%/animations/Hezrou/Hezrou-sounds~ ~override~
  END

//_____________________________________________________________________________________________________
// Necromental animation
 LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7F15 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END

  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% NECROMENTAL_ACIFER~ UNLESS ~NECROMENTAL_ACIFER~
  CLEAR_IDS_MAP

  COPY ~%MOD_FOLDER%/animations/Necromental/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Necromental~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END

//_____________________________________________________________________________________________________
// Mycomoth animation
 LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7F15 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END

  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% MYCOMOTH_ACIFER~ UNLESS ~MYCOMOTH_ACIFER~
  CLEAR_IDS_MAP

  COPY ~%MOD_FOLDER%/animations/Mycomoth/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Mycomoth~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END

//_____________________________________________________________________________________________________
// IA Displacer Beast animation
 LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7F3D slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END

  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#DISPLACER_BEAST~ UNLESS ~AC#DISPLACER_BEAST~
  CLEAR_IDS_MAP

  COPY ~%MOD_FOLDER%/animations/displacer_beast/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/displacer_beast~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
//_____________________________________________________________________________________________________
// EARTH_ELEMENTAL_HUGE animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END

  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#EARTH_ELEMENTAL_HUGE~ UNLESS ~AC#EARTH_ELEMENTAL_HUGE~
  CLEAR_IDS_MAP

  COPY ~%MOD_FOLDER%/animations/earth_elemental_huge_EE/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/earth_elemental_huge_EE~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
//_____________________________________________________________________________________________________
// RAVEN animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END

  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#RAVEN~ UNLESS ~AC#RAVEN~
  CLEAR_IDS_MAP

  COPY ~%MOD_FOLDER%/animations/raven_EE/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/raven_EE~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
//_____________________________________________________________________________________________________
// ROTHÉ animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#ROTHE~ UNLESS ~AC#ROTHE~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Rothe/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Rothe~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
//_____________________________________________________________________________________________________
// ROTHÉ GRAY animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#ROTHE_GRAY~ UNLESS ~AC#ROTHE_GRAY~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Rothe_gray/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Rothe_gray~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
 
  // Dwarven statue animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7f15 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% DWARVENSTATUE_ACIFER~ UNLESS ~DWARVENSTATUE_ACIFER~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Dwarven_statue/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Dwarven_statue~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END

//_____________________________________________________________________________________________________
// NWN_DEATH_TYRANT animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#NWN_DEATH_TYRANT~ UNLESS ~AC#NWN_DEATH_TYRANT~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/NWN_death_tyrant/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/NWN_death_tyrant~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
//_____________________________________________________________________________________________________
// NWN Allip animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#NWN_ALLIP~ UNLESS ~AC#NWN_ALLIP~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/NWN_Allip/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/NWN_Allip~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END

 //_____________________________________________________________________________________________________
// Golem Hammer animation
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#GOLEM_HAMMER~ UNLESS ~AC#GOLEM_HAMMER~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Golem_Hammer/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Golem_Hammer~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END

// NWN Bone Golem animation (used for Skelettin)
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#NWN_BONE_GOLEM~ UNLESS ~AC#NWN_BONE_GOLEM~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/NWN_BONE_GOLEM/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/NWN_BONE_GOLEM~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
// Verbeeg large animation (used for Maram's shadow)
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#VERBEEG_LARGE~ UNLESS ~AC#VERBEEG_LARGE~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Verbeeg_large_EE/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Verbeeg_large_EE~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
// drowned dead small animation (used for Duerghuls)
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#DROWNED_DEAD_SMALL~ UNLESS ~AC#DROWNED_DEAD_SMALL~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Drowned_dead_small/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Drowned_dead_small~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
 // HAMATULA
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END

  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#HAMATULA~ UNLESS ~AC#HAMATULA~
  CLEAR_IDS_MAP

  COPY ~%MOD_FOLDER%/animations/Hamatula/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Hamatula~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
 // Osyluth
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#OSYLUTH~ UNLESS ~AC#OSYLUTH~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Osyluth/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Osyluth~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
 // Pitfient_NWN
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#PITFIEND_NWN~ UNLESS ~AC#PITFIEND_NWN~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Pitfiend_NWN/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Pitfiend_NWN~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
//_____________________________________________________________________________________________________
// PST Thokola animation
 LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7F3D slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#THOKOLA_PST~ UNLESS ~AC#THOKOLA_PST~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Thokola_PST/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Thokola_PST~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
//_____________________________________________________________________________________________________
// NWN new Basilisk animation
   LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7d00 slotMax = 0x7dff RET slot END
 //LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7100 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#BASILISK_NWN~ UNLESS ~AC#BASILISK_NWN~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Basilisk_NWN/exxx.ini~ ~override/%hexNumber%.ini~
  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/Basilisk_NWN~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
  
// Doomsphere
  COPY ~%MOD_FOLDER%/animations/Doomsphere/AC#DOOMS.bmp~ ~override~
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7000 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#BEHOLDER_DOOMSPHERE~ UNLESS ~AC#BEHOLDER_DOOMSPHERE~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Doomsphere/exxx.ini~ ~override/%hexNumber%.ini~
  
// Gelugon
  COPY ~%MOD_FOLDER%/animations/Gelugon/AC#GELUG.bmp~ ~override~
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7000 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#GELUGON~ UNLESS ~AC#GELUGON~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Gelugon/exxx.ini~ ~override/%hexNumber%.ini~
  
// Earthwhisper
  COPY ~%MOD_FOLDER%/animations/Earthwhisper/AC#EARWI.bmp~ ~override~
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7000 slotMax = slotMin + 0xff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#EARTWHISPER~ UNLESS ~AC#EARTWHISPER~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Earthwhisper/exxx.ini~ ~override/%hexNumber%.ini~
  
// Lizardman_grey
  COPY ~%MOD_FOLDER%/animations/Lizardfolk_grey/AC#LIZGR.bmp~ ~override~
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
    FAIL ~No free creature animation slot found.~
  END
  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% AC#LIZARDMAN_GREY~ UNLESS ~AC#LIZARDMAN_GREY~
  CLEAR_IDS_MAP
  COPY ~%MOD_FOLDER%/animations/Lizardfolk_grey/exxx.ini~ ~override/%hexNumber%.ini~

//_____________________________________________________________________________________________________
// IWD's Animated plate bronze animation - just copy
  COPY ~silverrealms/animations/Animated_plate_bronze_IWD~         ~override~

//_____________________________________________________________________________________________________
// Neothelid animation - just copy
  COPY ~silverrealms/animations/Neothelid~         ~override~

//_____________________________________________________________________________________________________
// dragon white animation - just copy
  COPY ~silverrealms/animations/Dragon_white~         ~override~

//_____________________________________________________________________________________________________
// drider male animation - just copy
  COPY ~silverrealms/animations/Drider_male~         ~override~

//_____________________________________________________________________________________________________
// drider female animation - just copy
  COPY ~silverrealms/animations/Drider_female~         ~override~
//_____________________________________________________________________________________________________
// Yuan-Ti halfbreed animation - just copy
  COPY ~silverrealms/animations/Yuan_Ti_Half~         ~override~
  
//_____________________________________________________________________________________________________
// Abishai animations  - just copy
  COPY ~silverrealms/animations/Abishai_black~         ~override~
  COPY ~silverrealms/animations/Abishai_green~         ~override~
  COPY ~silverrealms/animations/Abishai_red~         ~override~
  COPY ~silverrealms/animations/Abishai_white~         ~override~
  
//_____________________________________________________________________________________________________
//  IWD's fire elemental animation (used for Magam paralelemental animation - just copy
  COPY ~silverrealms/animations/Elemental_Fire_IWD~         ~override~
  
//_____________________________________________________________________________________________________
//  IWD's water elemental animation - just copy
  COPY ~silverrealms/animations/Water_elemental_large_EE~         ~override~
  
//_____________________________________________________________________________________________________
//  IWD's Bugbear captain animation - just copy
  COPY ~silverrealms/animations/Bugbear_captain_IWD~         ~override~
  
//_____________________________________________________________________________________________________
//  IWD's Bugbear animation - just copy
  COPY ~silverrealms/animations/Bugbear_IWD~         ~override~

//_____________________________________________________________________________________________________
// verbeeg animation - copy iwd's verbeeg
  COPY ~silverrealms/animations/verbeeg_iwd_EE~         ~override~
//_____________________________________________________________________________________________________
// harpy animation - copy iwd's harpy
  COPY ~silverrealms/animations/harpy_iwd_EE~         ~override~
//_____________________________________________________________________________________________________
// vodyanoi animation - copy iwd's vodyanoi
  COPY ~silverrealms/animations/Vodyanoi_iwd_EE~         ~override~
//_____________________________________________________________________________________________________
// beetle_boring animation - copy
  COPY ~silverrealms/animations/Beetle_boring_iwd_EE~         ~override~
//_____________________________________________________________________________________________________
// umberhulk_elder animation - copy
  COPY ~silverrealms/animations/Umberhulk_elder_iwd_ee~         ~override~
  
//_____________________________________________________________________________________________________
// svirfneblin -all animations - copy
  COPY ~silverrealms/animations/svirfneblin_iwd~         ~override~

//_____________________________________________________________________________________________________
// feyr greater iwd2 animations - copy
  COPY ~silverrealms/animations/Feyr_greater_iwd2~         ~override~

//_____________________________________________________________________________________________________
// worg iwd2 animations - copy
  COPY ~silverrealms/animations/worg_iwd_EE~         ~override~

//_____________________________________________________________________________________________________
// lizardman green animation - copy
  COPY ~silverrealms/animations/Lizardman_green_iwd_EE~         ~override~
//_____________________________________________________________________________________________________
// hook horror animation - copy
  COPY ~silverrealms/animations/Hook_Horror_EE~         ~override~
  
// cyclops animation - copy
  COPY ~silverrealms/animations/Cyclops_IWD~         ~override~
  
// lizard king animation - copy
  COPY ~silverrealms/animations/Lizard_King_IWD~         ~override~


