// Silverrealms Spell Files

COPY ~silverrealms/spl/AC#ILWD.spl~         ~override~ // NEW #2 wild magic spell effect in ACIL30
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@6330) STR_VAR bam_file = AC#WILIL RET icon END
COPY_EXISTING ~AC#ILWD.spl~         ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 0 parameter2 = icon END

COPY ~silverrealms/spl/copy~         ~override~

COPY ~silverrealms/spl/AC#ILHE.spl~          ~override~ // Protective gem
SAY NAME1 @1155 SAY NAME2 @1155

COPY ~silverrealms/spl/AC#IL23.spl~          ~override~ // illusionary dragon breath
SAY NAME1 @1154 SAY NAME2 @1154

COPY ~silverrealms/spl/AC#2DDB.spl~          ~override~ // dwarven banshee wail
SAY NAME1 @1153 SAY NAME2 @1153

COPY ~silverrealms/spl/AC#ILWI.spl~            ~override~  // elder brain lobe spell effect
  SAY 0x9e @1151
  SAY 0xce @1152

COPY ~silverrealms/spl/AC#ILR6.spl~          ~override~ // drider ring spl file #1
SAY NAME1 @8108 SAY NAME2 @8108

COPY ~silverrealms/spl/AC#ILDR.spl~          ~override~ // drow ring spl file
SAY NAME1 @8106 SAY NAME2 @8106

COPY ~silverrealms/spl/AC#ILFF.spl~          ~override~ // faerie fire
SAY NAME1 @1150 SAY NAME2 @1150
SAY 0x18e @1150

COPY ~silverrealms/spl/AC#ILSH.spl~          ~override~ // shrieker shriek
SAY NAME1 @1149 SAY NAME2 @1149

ADD_PROJECTILE      ~silverrealms/pro/AC#HEZRU.PRO~ // Hezrou stench projectile
COPY ~silverrealms/spl/AC#HEZR.spl~            ~override~  // Hezrou stench
  SAY NAME1 @1142
  SAY 0xce @1142
  WRITE_SHORT   0x98 ~%AC#HEZRU%~

COPY ~silverrealms/spl/AC#IL71.spl~          ~override~ // dragon wraith breath
SAY NAME1 @1148 SAY NAME2 @1148

COPY ~silverrealms/spl/AC#ILPH.spl~          ~override~ // phosphor dragon hit

ADD_PROJECTILE      ~silverrealms/pro/AC#NEOM.PRO~ // neothelid's musous slime projectile
COPY ~silverrealms/spl/AC#NEOM.spl~          ~override~ // neothelid's musous slime
  WRITE_SHORT   0x98 ~%AC#NEOM%~

ADD_PROJECTILE      ~silverrealms/pro/AC#NEOB.PRO~ // neothelid's poisonous breath projectile
COPY ~silverrealms/spl/AC#NEOB.spl~          ~override~ // neothelid's poisonous breath
  SAY NAME1 @1147 SAY NAME2 @1147
  WRITE_SHORT   0x98 ~%AC#NEOB%~


COPY ~silverrealms/spl/AC#ILD1.spl~          ~override~ // intellect devourer's insinuation
SAY NAME1 @1146 SAY NAME2 @1146

COPY ~silverrealms/spl/AC#NEO4.spl~          ~override~ // neothelid's insinuation
SAY NAME1 @1146 SAY NAME2 @1146

COPY ~silverrealms/spl/AC#NEO3.spl~          ~override~ // neothelid's control body
SAY NAME1 @1145 SAY NAME2 @1145

COPY ~silverrealms/spl/AC#NEO2.spl~          ~override~ // neothelid's telekinesis
SAY NAME1 @1144 SAY NAME2 @1144

COPY ~silverrealms/spl/AC#NEO1.spl~          ~override~ // neothelid's taste link
SAY NAME1 @1143 SAY NAME2 @1143

COPY ~silverrealms/spl/AC#NEOT.spl~          ~override~ // unsummon magical sword

COPY ~silverrealms/spl/AC#HAMG.spl~          ~override~ // pounding force, hammer golem's special ability
SAY NAME1 @1139 SAY NAME2 @1139

COPY ~silverrealms/spl/AC#SPKIN.spl~          ~override~
SAY NAME1 @165 SAY NAME2 @165

COPY ~silverrealms/spl/AC#HSON.spl~          ~override~ //Harpysong
SAY NAME1 @590 SAY NAME2 @590

COPY ~silverrealms/spl/AC#WAND7.spl~          ~override~
SAY NAME1 @790 SAY NAME2 @790

COPY ~silverrealms/spl/AC#MAL2.spl~          ~override~
SAY NAME1 @960 SAY NAME2 @960

COPY ~silverrealms/spl/AC#I713.spl~          ~override~   // Protection from Fire, 15' radius (Wizards spell compendium volume III, p. 702)
SAY NAME1 @1024 SAY NAME2 @1024

COPY ~silverrealms/spl/AC#DRL1.spl~          ~override~   // Dracolich Gaze attack: Hold
SAY NAME1 @1126 SAY NAME2 @1126

COPY ~silverrealms/spl/AC#GDRK.spl~          ~override~  // Globe of darkness
SAY NAME1 @1128 SAY NAME2 @1128

COPY ~silverrealms/spl/AC#GLDRK.spl~          ~override~  // Globe of darkness
SAY NAME1 @1128 SAY NAME2 @1128

COPY ~silverrealms/spl/AC#67IW.spl~          ~override~  // Gelugon: Wall of ice
SAY NAME1 @1130 SAY NAME2 @1130

COPY ~silverrealms/spl/AC#24GC.spl~          ~override~  // Cloak of Gaer (Demihuman Deities, p.33)
SAY NAME1 @1131 SAY NAME2 @1131

COPY ~silverrealms/spl/AC#SPW2.spl~          ~override~  // Protection from poison (Wizard)  (Spellbound, p.95)
SAY NAME1 @8026 SAY NAME2 @8026
SAY DESC @8027
SAY UNIDENTIFIED_DESC @8027

COPY ~silverrealms/spl/AC#2DB1.spl~          ~override~  // dwarven banshee: curse (gaze attack)
SAY NAME1 @1132 SAY NAME2 @1132

COPY ~silverrealms/spl/AC#2DB2.spl~          ~override~  // dwarven banshee: cursed battlecry
SAY NAME1 @1133 SAY NAME2 @1133

COPY ~silverrealms/spl/AC#B_EN.spl~          ~override~  // doomsphere: enervation
SAY NAME1 @1134 SAY NAME2 @1134

COPY ~silverrealms/spl/AC#B_BS.spl~          ~override~  // doomsphere: boneshatter
SAY NAME1 @1135 SAY NAME2 @1135

COPY ~silverrealms/spl/AC#B_WI.spl~          ~override~  // doomsphere: withering
SAY NAME1 @1136 SAY NAME2 @1136

COPY ~silverrealms/spl/AC#B_CR.spl~          ~override~  // doomsphere: chill ray
SAY NAME1 @1137 SAY NAME2 @1137

COPY ~silverrealms/spl/AC#EW_1.spl~          ~override~  // earth whisper: avarice
SAY NAME1 @1138 SAY NAME2 @1138