IF
  Global("AC#IL_ForgeRDragScales","GLOBAL",1) // player decided to craft item
  Global("ForgeStuff","GLOBAL",1) // crafting cutscene has completed
THEN
  RESPONSE #100
    SetGlobal("AC#IL_ForgeRDragScales","GLOBAL",2)
    SetGlobal("ForgeStuff","GLOBAL",0)
    TakePartyItemNum("AC#ILRDS",3) 
    DestroyItem("AC#ILRDS") 
    DestroyItem("AC#ILRDS") 
    DestroyItem("AC#ILRDS") 
    GiveItemCreate("AC#ILRLA",Player1,1,0,0) // give completed item
    SetGlobal("ForgeItem","GLOBAL",1) // will trigger "done crafting" dialogue state 57 from Cromwell
    ActionOverride("wsmith01",StartDialogueNoSet([PC])) // resume dialogue with Cromwell
END

