IF
	Global("AC#IltkazarQuest#2","GLOBAL",2)
THEN
	RESPONSE #100
		SetGlobal("AC#IltkazarQuest#2","GLOBAL",3)
		SpawnPtDeactivate("SpawnPoint3")
		CreateCreature("AC#4ITH2",[2169.2359],3) // Thief
		CreateCreature("ac#s#cd3",[2078.2403],11) // Larkonlan
		CreateCreature("ac#s#cd4",[2034.2433],11) // Fighter
END

IF
	//Dead("AC#4ITH2") // Thief
	//Dead("ac#s#cd3") // Larkonlan
	//Dead("ac#s#cd4") // Fighter	
	PartyHasItem("AC#SRBK1")
	Global("AC#IltkazarQuest#2","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("AC#IltkazarQuest#2","GLOBAL",10)
		//EraseJournalEntry(@20061)
		//EraseJournalEntry(@20063)
		//EraseJournalEntry(@20064)
		AddJournalEntry(@20062,QUEST)
		SpawnPtActivate("SpawnPoint3")
END






