IF
	OR(2)
		Entered([ANYONE])
		Opened([ANYONE])
THEN
	RESPONSE #100
		DisplayString(LastTrigger,999999)
		CreateVisualEffectObject("ICMAGICH",Myself)
		CreateVisualEffectObject("SPFIREPI",Myself)
		CreateCreatureObject("ELFIRG01",LastTrigger,0,0,0)
END

/*
IF
  Opened(Myself)
  Global("ACIL1V_OPEN","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("ACIL1V_OPEN","LOCALS",1)
    DisplayString(Myself,999999)
    CreateCreature("ELFIR01",[-1.-1],0)
END
*/

/*
IF
	Opened([ANYONE])
        Global("ACIL1V_OPEN","LOCALS",0)
THEN
	RESPONSE #100
                SetGlobal("ACIL1V_OPEN","LOCALS",1)
                DisplayString(Myself,999999) // Ihr öffnet die Tür des Hochofens, und aus dessen Inneren springt plötzlich ein wütender Feuerelementar heraus!
		CreateCreature("ELFIR01",[-1.-1],0) // Feuerelementar
END
*/


