/*

Dieses Skript transportiert die Spieler aus Area AR1100 (Dämmerwaldtal) zurück inach Imnestal
*/
IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		FadeToColor([30.0],0)
		Wait(1)
		LeaveAreaLUAPanic("AR1100","",[3705.3427],0)
		LeaveAreaLUA("AR1100","",[3705.3427],6)
		ActionOverride(Player2,LeaveAreaLUA("AR1100","",[3705.3427],13))
		ActionOverride(Player3,LeaveAreaLUA("AR1100","",[3705.3427],13))
		ActionOverride(Player4,LeaveAreaLUA("AR1100","",[3705.3427],13))
		ActionOverride(Player5,LeaveAreaLUA("AR1100","",[3705.3427],13))
		ActionOverride(Player6,LeaveAreaLUA("AR1100","",[3705.3427],13))
		MultiPlayerSync()
		MoveViewPoint([3705.3427],INSTANT)
		FadeFromColor([30.0],0)
		EndCutSceneMode()
END





