/*

Dieses Skript transportiert die Spieler aus Area ACIL1D (Dämmerwaldtal) zurück nach ACIL10 (Wailing Dwarf)
*/
IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		FadeToColor([30.0],0)
		Wait(1)
		LeaveAreaLUAPanic("ACIL10","",[3788.2105],0)
		LeaveAreaLUA("ACIL10","",[3788.2105],6)
		ActionOverride(Player2,LeaveAreaLUA("ACIL10","",[3788.2105],13))
		ActionOverride(Player3,LeaveAreaLUA("ACIL10","",[3788.2105],13))
		ActionOverride(Player4,LeaveAreaLUA("ACIL10","",[3788.2105],13))
		ActionOverride(Player5,LeaveAreaLUA("ACIL10","",[3788.2105],13))
		ActionOverride(Player6,LeaveAreaLUA("ACIL10","",[3788.2105],13))
		MultiPlayerSync()
		MoveViewPoint([3788.2105],INSTANT)
		FadeFromColor([30.0],0)
		EndCutSceneMode()
END





