IF
	Clicked([ANYONE])
	!Range(LastTrigger,12)
THEN
	RESPONSE #100
		DisplayString(Myself,999995) // Aus dieser Entfernung könnt Ihr nichts erkennen.
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	Race(LastTrigger,DWARF)
THEN
	RESPONSE #100
		DisplayString(Myself,999999) /* Diese Bronzeplatte zeigt das Symbol eines Gedankenschinders, um den sieben Edelsteine angeordnet sind. Auf der Umrandung steht in Zwergenrunen geschrieben:
"Der Schutzpatron Korolnors verfiel durch Hinterlist, Verrat und dem Einfluss der Illithiden dem Wahnsinn." */

END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	CheckStatGT(LastTrigger,50,LORE)

THEN
	RESPONSE #100
		DisplayString(Myself,999999)  /* DDiese Bronzeplatte zeigt das Symbol eines Gedankenschinders, um den sieben Edelsteine angeordnet sind. Auf der Umrandung steht in Zwergenrunen geschrieben:
"Der Schutzpatron Korolnors verfiel durch Hinterlist, Verrat und dem Einfluss der Illithiden dem Wahnsinn."*/
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	PartyHasItemIdentified("AC#BKDWF") // Die Schrift und Sprache der Zwerge

THEN
	RESPONSE #100
		DisplayString(Myself,999999) /* Diese Bronzeplatte zeigt das Symbol eines Gedankenschinders, um den sieben Edelsteine angeordnet sind. Auf der Umrandung steht in Zwergenrunen geschrieben:
"Der Schutzpatron Korolnors verfiel durch Hinterlist, Verrat und dem Einfluss der Illithiden dem Wahnsinn.*/
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	CheckStatLT(LastTrigger,51,LORE)

THEN
	RESPONSE #100
		DisplayString(Myself,999998) // Diese Bronzeplatte zeigt das Symbol eines Gedankenschinders, um den sieben Edelsteine angeordnet sind. Auf der Umrandung sind Zwergenrunen eingraviert, die Ihr nicht entziffern könnt.
END

