IF
	Clicked([ANYONE])
	Race(LastTrigger,DWARF)
THEN
	RESPONSE #100
		DisplayString(Myself,999999) /* ~Diese Brücke wurde eindeutig von Zwergenhand erbaut und scheint früher über den reißenden Fluss geführt zu haben. Leider ist sie schon seit langem eingestürzt. Ihr erkennt, dass sie wohl mithilfe einer Vorrichtung zum Einsturz gebracht worden ist, um Angreifer mit in die Tiefe zu reißen.~ */

END

IF
	Clicked([ANYONE])
	CheckStatGT(LastTrigger,50,LORE)

THEN
	RESPONSE #100
		DisplayString(Myself,999998)  /* ~Diese Brücke scheint früher über den reißenden Fluss geführt zu haben. Leider ist sie schon seit langem eingestürzt. Ihr erkennt, dass sie wohl mithilfe einer Vorrichtung zum Einsturz gebracht worden ist, um Angreifer mit in die Tiefe zu reißen.~ */
END


IF
	Clicked([ANYONE])
	CheckStatLT(LastTrigger,51,LORE)

THEN
	RESPONSE #100
		DisplayString(Myself,999997) // ~Diese Brücke scheint früher über den reißenden Fluss geführt zu haben. Leider ist sie schon seit langem eingestürzt.~
END

