IF
	Clicked([ANYONE])
	!Range(LastTrigger,12)
THEN
	RESPONSE #100
		DisplayString(Myself,999995) // Aus dieser Entfernung könnt Ihr nichts erkennen.
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	Race(LastTrigger,DWARF)
THEN
	RESPONSE #100
		DisplayString(Myself,999999) /* Auf diesem großen Stein steht in Zwergenrunen geschrieben:
"Die übrigen Riesen flohen in die Riesenlaufberge, was diesem Gebirge bis heute seinen Namen gab. Karlyn beschloss, an dieser Furt die neue Festung für seinen Clan zu errichten. Um die Riesen immer an ihre Niederlage zu erinnern, ließ er ein riesiges Standbild eines Zwergenwächters errichten, welches nach Osten sieht, schon aus der Weite für alle Wesen zu hören ist und auf ewig ruft: Fürchtet den Zorn der Zwerge!" */

END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	CheckStatGT(LastTrigger,50,LORE)

THEN
	RESPONSE #100
		DisplayString(Myself,999999)  /* AAuf diesem großen Stein steht in Zwergenrunen geschrieben:
"Die übrigen Riesen flohen in die Riesenlaufberge, was diesem Gebirge bis heute seinen Namen gab. Karlyn beschloss, an dieser Furt die neue Festung für seinen Clan zu errichten. Um die Riesen immer an ihre Niederlage zu erinnern, ließ er ein riesiges Standbild eines Zwergenwächters errichten, welches nach Osten sieht, schon aus der Weite für alle Wesen zu hören ist und auf ewig ruft: Fürchtet den Zorn der Zwerge!"*/
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	PartyHasItemIdentified("AC#BKDWF") // Die Schrift und Sprache der Zwerge

THEN
	RESPONSE #100
		DisplayString(Myself,999999) /* Auf diesem großen Stein steht in Zwergenrunen geschrieben:
"Die übrigen Riesen flohen in die Riesenlaufberge, was diesem Gebirge bis heute seinen Namen gab. Karlyn beschloss, an dieser Furt die neue Festung für seinen Clan zu errichten. Um die Riesen immer an ihre Niederlage zu erinnern, ließ er ein riesiges Standbild eines Zwergenwächters errichten, welches nach Osten sieht, schon aus der Weite für alle Wesen zu hören ist und auf ewig ruft: Fürchtet den Zorn der Zwerge!"*/
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	CheckStatLT(LastTrigger,51,LORE)

THEN
	RESPONSE #100
		DisplayString(Myself,999998) // Auf diesem großen Stein sind zahlreiche Zwergenrunen eingraviert, die Ihr nicht entziffern könnt.
END

