/*
AC#29MI3

Spiegelfalle AC#29MI3 in der Betrachterhöhle
*/
IF
	Entered([0.0.0.0.0.SUMMONED])
	!Dead("AC#BEH06")
	!StateCheck(LastTrigger,STATE_INVISIBLE)
	!StateCheck(LastTrigger,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
                IncrementGlobal("Trigger_AC#29MI3","ACIL29",1)
                ActionOverride("AC#BEH06",ReallyForceSpell("AC#29MI3",WIZARD_DEATH_SPELL))
                SmallWait(20)
		ReallyForceSpell(LastTrigger,WIZARD_DEATH_SPELL)
END

IF
	Entered([PC])
	!Dead("AC#BEH06")
	!StateCheck(LastTrigger,STATE_INVISIBLE)
	!StateCheck(LastTrigger,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
                IncrementGlobal("Trigger_AC#29MI3","ACIL29",1)
                ActionOverride("AC#BEH06",ForceSpell("AC#29MI3",BEHOLDER_DEATH_RAY))
                SmallWait(20)
		ForceSpell(LastTrigger,BEHOLDER_DEATH_RAY)
END


