IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		//FadeToColor([30.0],0)
		//Wait(2)
		LeaveAreaLUAPanic("ACIL02","",[1622.1347],0)
		LeaveAreaLUA("ACIL02","",[1622.1347],0)
		ActionOverride(Player2,LeaveAreaLUA("ACIL02","",[1628.1341],10))
		ActionOverride(Player3,LeaveAreaLUA("ACIL02","",[1620.1349],10))
		ActionOverride(Player4,LeaveAreaLUA("ACIL02","",[1625.1342],10))
		ActionOverride(Player5,LeaveAreaLUA("ACIL02","",[1619.1341],10))
		ActionOverride(Player6,LeaveAreaLUA("ACIL02","",[1627.1351],10))
		MultiPlayerSync()
		AddXPObject(Player1,2000)
		AddXPObject(Player2,2000)
		AddXPObject(Player3,2000)
		AddXPObject(Player4,2000)
		AddXPObject(Player5,2000)
		AddXPObject(Player6,2000)
		Wait(1)
		EndCutSceneMode()
		FadeFromColor([30.0],0)
END


