IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	Global("AC#23Book02","ACIL23",0)
THEN
	RESPONSE #100
		CreateCreatureImpassable("AC#23BO2",[2271.319],13)
		SetGlobal("AC#23Book02","ACIL23",1)
		ActionOverride("AC#23BO2",StartDialogueNoSet([PC]))
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	Global("AC#23Book02","ACIL23",1)
THEN
	RESPONSE #100
		ActionOverride("AC#23BO2",StartDialogueNoSet([PC]))
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,10)
THEN
	RESPONSE #100
		DisplayString(Myself,14702) // Ihr seid zu weit entfernt, um das zu benutzen.
END


