IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	Global("AC#23Book05","ACIL23",0)
THEN
	RESPONSE #100
		CreateCreatureImpassable("AC#23BO5",[2396.325],13)
		SetGlobal("AC#23Book05","ACIL23",1)
		ActionOverride("AC#23BO5",StartDialogueNoSet([PC]))
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	Global("AC#23Book05","ACIL23",1)
THEN
	RESPONSE #100
		ActionOverride("AC#23BO5",StartDialogueNoSet([PC]))
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,10)
THEN
	RESPONSE #100
		DisplayString(Myself,14702) // Ihr seid zu weit entfernt, um das zu benutzen.
END


