IF
	OR(3)
		AttackedBy([GOODCUTOFF],DEFAULT)
		Allegiance("AC#24DAE",ENEMY)
		Global("Drowfight","ACIL24",1)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	!Dead("AC#24DAE")
	!See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
THEN
	RESPONSE #100
		MoveToObject(NearestEnemyOf("AC#24DAE"))	
END

IF
	Global("VhaeraunLeaves","ACIL24",10)
THEN
	RESPONSE #100
        CreateVisualEffectObject("SPDIMNDR",Myself)
	    Wait(1)
	    DestroySelf()
END