// When PCs too far away
IF
	Clicked([ANYONE])
	!Range(LastTrigger,12)
THEN
	RESPONSE #100
		DisplayString(Myself,999995) // Aus dieser Entfernung könnt Ihr nichts erkennen.
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	Global("Tethir_Movie","ACIL46",2)
THEN
	RESPONSE #100
		DisplayString(Myself,999994) // ~Ihr habt bereits alles Wissen erworben, um Eure Reise fortzusetzen.~
END

// Not nighttime
// PC elf
IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	!TimeOfDay(NIGHT)
	OR(2)
	Race(LastTrigger,ELF)
	Race(LastTrigger,HALF_ELF)
THEN
	RESPONSE #100
		DisplayString(Myself,999999) // ~Auf dieser uralten Säule sind Skizzen und Anmerkungen in der Sprache Eurer Vorfahren, der Elfen, eingraviert. Sie zeugen von dem mächtigen Reich, das die Elfen in diesem Teil Faeruns einmal beherrscht haben. Auf dem Boden scheint eine riesige Landkarte mit zahlreichen längst vergessenen Orten der Elfengemeinden aufgezeichnet zu sein. Allerdings könnt Ihr bei Tageslicht die feinen Strukturen kaum erkennen.~
END

// Not nighttime
// PC no elf
// PC High Lore

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	!TimeOfDay(NIGHT)
	CheckStatGT(LastTrigger,50,LORE)
THEN
	RESPONSE #100
		DisplayString(Myself,999998) // ~Auf dieser uralten Säule sind Skizzen und Anmerkungen in der Sprache der Elfen, die Ihr einmal gelernt habt, eingraviert. Sie zeugen von dem mächtigen Reich, das die Elfen in diesem Teil Faeruns einmal beherrscht haben. Auf dem Boden scheint eine riesige Landkarte mit zahlreichen längst vergessenen Orten der Elfengemeinden aufgezeichnet zu sein. Allerdings könnt Ihr bei Tageslicht die feinen Strukturen kaum erkennen.~
END

// Not nighttime

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	CheckStatLT(LastTrigger,51,LORE)
	!TimeOfDay(NIGHT)
THEN
	RESPONSE #100
		DisplayString(Myself,999997) // ~Auf dieser uralten Säule sind Skizzen und Anmerkungen in einer feinen Schrift eingraviert, die Ihr jedoch nicht entziffern könnt. Auf dem Boden scheint eine riesige Landkarte mit zahlreichen längst vergessenen Orten aufgezeichnet zu sein. Allerdings könnt Ihr bei Tageslicht die feinen Strukturen kaum erkennen.~
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
        TimeOfDay(NIGHT)
        Global("Tethir_Movie","ACIL46",0)
THEN
	RESPONSE #100
                SetGlobal("Tethir_Movie","ACIL46",1)
		DisplayString(Myself,999993) // ~Bei Mondschein strahlt die Säule in einem hellen Licht, und auch die Zeichnungen auf der Landkarte stechen deutlich hervor. Wenn Ihr möchtet, könnt Ihr den Stein erneut berühren, um die Karte nach dem von Euch gesuchten Ort gezielt in Augenschein zu nehmen.~
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
        TimeOfDay(NIGHT)
        Global("Tethir_Movie","ACIL46",1)
THEN
	RESPONSE #100
                SetGlobal("Tethir_Movie","ACIL46",2)
	        ClearAllActions()
	        StartCutSceneMode()
       		//SetInterrupt(FALSE)
		DisplayString(Myself,999996) // ~Mit einem Mal entdeckt Ihr auf der Karte den Ort, den Mith Barak in Eurem Traum erwähnt hatte - der Ort, an dem Tethir den Drachen erschlagen und den Ihr so lange gesucht habt...~
		CreateVisualEffect("SPSTRENH",[1080.752])
                Wait(2)
		CreateVisualEffectObject("SPSTRENH",LastTrigger)
		Wait(4)
		AddexperienceParty(10000)
		EndCutSceneMode()
                StartMovie("AC#46MVE")
		//SetInterrupt(TRUE)
END

