IF
  OR(2)
  !See([PC])
  !Range([PC],15)
THEN
  RESPONSE #100
    ClearActions(Myself)
    ActionOverride("AC#52DW2",ClearActions(Myself))
    Continue()
END

IF
	HitBy("AC#52DW2",CRUSHING)
        RandomNum(3,1)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,999999)
		Wait(2)
		ActionOverride("AC#52DW2",DisplayStringHead(Myself,999998))
                Continue()
END

IF
	HitBy("AC#52DW2",CRUSHING)
        RandomNum(3,2)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,999997)
		Wait(2)
		ActionOverride("AC#52DW2",DisplayStringHead(Myself,999996))
                Continue()
END

IF
  See([PC])
  Range(LastSeenBy(Myself),15)
THEN
  RESPONSE #50
    DisplayStringHead(Myself,999997)
    ActionOverride("AC#52DW3",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW2",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW3",AttackOneRound("AC#52DW2")
    ActionOverride("AC#52DW2",AttackOneRound("AC#52DW3")
  RESPONSE #50
    ActionOverride("AC#52DW2",DisplayStringHead(Myself,999996))
    ActionOverride("AC#52DW3",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW2",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW3",AttackOneRound("AC#52DW2")
    ActionOverride("AC#52DW2",AttackOneRound("AC#52DW3")
  RESPONSE #50
    DisplayStringHead(Myself,999999)
    ActionOverride("AC#52DW3",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW2",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW3",AttackOneRound("AC#52DW2")
    ActionOverride("AC#52DW2",AttackOneRound("AC#52DW3")
  RESPONSE #50
    ActionOverride("AC#52DW2",DisplayStringHead(Myself,999998))
    ActionOverride("AC#52DW3",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW2",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW3",AttackOneRound("AC#52DW2")
    ActionOverride("AC#52DW2",AttackOneRound("AC#52DW3")
  RESPONSE #100
    ActionOverride("AC#52DW3",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW2",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW3",AttackOneRound("AC#52DW2")
    ActionOverride("AC#52DW2",AttackOneRound("AC#52DW3")
END

IF
  See([PC])
  Range(LastSeenBy(Myself),15)
THEN
  RESPONSE #100
    ActionOverride("AC#52DW3",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW2",DialogueInterrupt(FALSE))
    ActionOverride("AC#52DW3",AttackOneRound("AC#52DW2")
    ActionOverride("AC#52DW2",AttackOneRound("AC#52DW3")
END














