IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	Global("Travel_ACIL57","ACIL58",0)
THEN
	RESPONSE #100
                SetGlobal("Travel_ACIL57","ACIL58",1)
                DisplayString(Myself,999999)
                ClearAllActions()
		StartCutSceneMode()
		Wait(2)
		StartCutScene("ac#cut57")
END

IF
	Global("Travel_ACIL57","ACIL58",1)
THEN
	RESPONSE #100
                SetGlobal("Travel_ACIL57","ACIL58",2)
		TriggerActivation("Travel_ACIL57",FALSE)
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,10)
THEN
	RESPONSE #100
		DisplayString(Myself,14702)
END




