IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	Global("AC#Skull","ACIL31",0)
THEN
	RESPONSE #100
		DisplayString(Myself,999997) // ~In der Mitte dieses seltsamen Schiffes befindet sich ein Schädel, der dem Kopf eines Gedankenschinders nachempfunden ist. Er scheint etwas mit dem Steuermechanismus des Vehikels zu tun zu haben, denn eine starke Energie geht von dem Objekt aus.~
		SetGlobal("AC#Skull","ACIL31",1)
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	Global("AC#Skull","ACIL31",1)
THEN
	RESPONSE #100
		DisplayString(Myself,999996) // ~Intuitiv berührt Ihr den Schädel, und mit einem Ruck verschwimmt die Welt um Euch herum. Ihr scheint mit dem unnatürlichen Geist des Schiffes zu verschmelzen, sodass Ihr die Richtung des Schiffes nur mit Euren Gedanken lenken könntet.~
		CreateCreatureImpassable("AC#Skul1",[1878.821],13)
		SetGlobal("AC#Skull","ACIL31",2)
		ActionOverride("AC#Skul1",StartDialogueNoSet([PC]))
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	Global("AC#Skull","ACIL31",2)
THEN
	RESPONSE #100
		ActionOverride("AC#Skul1",StartDialogueNoSet([PC]))
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,10)
THEN
	RESPONSE #100
		DisplayString(Myself,14702)
END


