IF
        Entered([ANYONE])
        GLOBAL("ACIL81_warning","ACIL81",0)
THEN
    RESPONSE #100
         ClearAllActions()
         DisplayString (Myself,999999)
         SetGlobal("ACIL81_warning","ACIL81",1)
END

IF
        Entered([ANYONE])
        GLOBAL("ACIL81_warning","ACIL81",1)
THEN
    RESPONSE #100
		ForceSpell(LastTrigger,WIZARD_FINGER_OF_DEATH)
		//ForceSpell(LastTrigger,WIZARD_IMPRISONMENT)
END

