IF
	Global("AC#DragonAttacked","GLOBAL",6)
THEN
	RESPONSE #100
                SetGlobal("AC#DragonAttacked","GLOBAL",7)
                ClearAllActions()
                ForceSpell(Myself,DO_NOTHING)
                DetectSecretDoor("DOOR01")
                Wait(1)
		StartDialogueNoSet([PC])
END

IF
	Global("AC#DragonAttacked","GLOBAL",5)
	RandomNum(3,1)
THEN
	RESPONSE #100
	   ForceSpell(Myself,DO_NOTHING)  // SPIN905.SPL (No such index)
END

