/*

Dieses Skript transportiert die Spieler aus Area ACIL54  in den Brunnen (ACIL5C)
*/
IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		FadeToColor([30.0],50)
		Wait(1)
		LeaveAreaLUAPanic("ACIL5C","",[319.502],0)
		LeaveAreaLUA("ACIL5C","",[319.502],6)
		ActionOverride(Player2,LeaveAreaLUA("ACIL5C","",[319.502],6))
		ActionOverride(Player3,LeaveAreaLUA("ACIL5C","",[319.502],6))
		ActionOverride(Player4,LeaveAreaLUA("ACIL5C","",[319.502],6))
		ActionOverride(Player5,LeaveAreaLUA("ACIL5C","",[319.502],6))
		ActionOverride(Player6,LeaveAreaLUA("ACIL5C","",[319.502],6))
		MultiPlayerSync()
		MoveViewPoint([319.502],INSTANT)
		Wait(1)
		FadeFromColor([30.0],150)
		EndCutSceneMode()
END