IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	Global("Coffin1","ACIL1U",0)
THEN
	RESPONSE #100
		DisplayString(Myself,35811) // Nachdem Ihr den Vampir besiegt habt, hat er sich in seinen Sarg zurückgezogen. Wenn Ihr über einen Holzpflock verfügt, könnt Ihr versuchen, ihn zu töten.
		SetGlobal("Coffin1","ACIL1U",1)
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	PartyHasItem("MISC6W") // Holzpflock
	Global("Coffin1","ACIL1U",1)
THEN
	RESPONSE #100
		DisplayString(Myself,35847) // Ihr stoßt den Holzpflock durch das finstere Herz des Vampirs. Diese Kreatur wird sich nie mehr vom Blut anderer Wesen ernähren.
		SetGlobal("Coffin1","ACIL1U",2)
		AddexperienceParty(9000)
		PlaySound("VAMPP07")
		TakePartyItemNum("misc6w",1) // Holzpflock
		DestroyItem("misc6w") // Holzpflock
		CreateVisualEffectObject("SPDEATH3",Myself)
		Wait(1)
		CreateVisualEffectObject("SPFLESH2",Myself)
		Wait(1)
		DisplayString(Myself,999999) // Nachdem der gequälte Schrei des Vampirs verhallt ist, stellt Ihr fest, dass seine Leiche einen Ring am rechten Zeigefinger trägt. Ihr nehmt den Ring und steckt ihn ein.
		GiveItemCreate("AC#RING9",LastTrigger,0,0,0) // Ring der Überlieferung
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
	Global("Coffin1","ACIL1U",2)
THEN
	RESPONSE #100
		DisplayString(Myself,35849) // Der Vampir ist endgültig tot, und der Sarg riecht nach Verwesung. Es gibt hier nichts mehr zu tun.
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,12)
THEN
	RESPONSE #100
		DisplayString(Myself,35811) // Nachdem Ihr den Vampir besiegt habt, hat er sich in seinen Sarg zurückgezogen. Wenn Ihr über einen Holzpflock verfügt, könnt Ihr versuchen, ihn zu töten.
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,12)
THEN
	RESPONSE #100
		DisplayString(Myself,14702) // Ihr seid zu weit entfernt, um das zu benutzen.
END













