/*

Dieses Skript transportiert die Spieler aus Area ACIL50  vor ACIL27, um nach Barakuir zu gelangen
*/
IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		ActionOverride("AC#ELER2",EscapeArea())
		ActionOverride("AC#50BSM",EscapeArea())
		ActionOverride("AC#50BSM",EscapeArea())
		Wait(1)
		LeaveAreaLUAPanic("ACIL20","",[3783.2493],0)
		LeaveAreaLUA("ACIL20","",[3783.2493],6)
		ActionOverride(Player2,LeaveAreaLUA("ACIL20","",[3783.2493],6))
		ActionOverride(Player3,LeaveAreaLUA("ACIL20","",[3783.2493],6))
		ActionOverride(Player4,LeaveAreaLUA("ACIL20","",[3783.2493],6))
		ActionOverride(Player5,LeaveAreaLUA("ACIL20","",[3783.2493],6))
		ActionOverride(Player6,LeaveAreaLUA("ACIL20","",[3783.2493],6))
		ActionOverride("AC#HATH1",JumpToPoint([3582.2486]))
		MultiPlayerSync()
		MoveViewPoint([3783.2493],INSTANT)
		Wait(1)
		FadeFromColor([40.0],150)
		SetGlobal("AC#RC_Sorni_Fourth","GLOBAL",6)
		EndCutSceneMode()
		ActionOverride("AC#HATH1",Face(13))
		Wait(1)
		ActionOverride("AC#HATH1",StartDialogNoSet(Player1))
END

//OLD: Problem: DOOR to ACIL27 isn't closed
/*
IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		//ActionOverride("AC#BRES1",EscapeArea())
		ActionOverride("AC#ELER2",EscapeArea())
		ActionOverride("AC#50BSM",EscapeArea())
		ActionOverride("AC#50BSM",EscapeArea())
		Wait(1)
		LeaveAreaLUAPanic("ACIL20","",[3783.2493],0)
		LeaveAreaLUA("ACIL20","",[3783.2493],6)
		ActionOverride(Player2,LeaveAreaLUA("ACIL20","",[3783.2493],6))
		ActionOverride(Player3,LeaveAreaLUA("ACIL20","",[3783.2493],6))
		ActionOverride(Player4,LeaveAreaLUA("ACIL20","",[3783.2493],6))
		ActionOverride(Player5,LeaveAreaLUA("ACIL20","",[3783.2493],6))
		ActionOverride(Player6,LeaveAreaLUA("ACIL20","",[3783.2493],6))
		ActionOverride("AC#HATH1",JumpToPoint([3900.2558]))
		MultiPlayerSync()
		MoveViewPoint([3783.2493],INSTANT)
		Wait(1)
		FadeFromColor([30.0],150)
		SetGlobal("AC#RC_Sorni_Fourth","GLOBAL",6)
		EndCutSceneMode()
		ActionOverride("AC#HATH1",StartDialogueNoSet(Player1))
END
*/