/*

Dieses Skript transportiert die Spieler aus Area ACIL01 (Ravomirs Cave) zurück ins Dämmerwaldtal
*/
IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		FadeToColor([30.0],0)
		Wait(1)
		LeaveAreaLUAPanic("ACIL1D","",[549.2225],0)
		LeaveAreaLUA("ACIL1D","",[549.2225],6)
		ActionOverride(Player2,LeaveAreaLUA("ACIL1D","",[419.451],13))
		ActionOverride(Player3,LeaveAreaLUA("ACIL1D","",[419.451],13))
		ActionOverride(Player4,LeaveAreaLUA("ACIL1D","",[419.451],13))
		ActionOverride(Player5,LeaveAreaLUA("ACIL1D","",[419.451],13))
		ActionOverride(Player6,LeaveAreaLUA("ACIL1D","",[419.451],13))
		MultiPlayerSync()
		MoveViewPoint([419.451],INSTANT)
		EndCutSceneMode()
END

