IF
	//Detect([PC])
	OnCreation()
	Global("AC#Deer_Injured","ACIL1W",0)
THEN
	RESPONSE #100
		SetGlobal("AC#Deer_Injured","ACIL1W",1)
		PlayDeadInterruptable(1000000)
END

IF
        Global("HealedMe","ACIL1W",0)
	See([PC])
	OR(4)
	SpellCastOnMe([ANYONE],CLERIC_HEAL)
	SpellCastOnMe([ANYONE],CLERIC_CURE_LIGHT_WOUNDS)
        SpellCastOnMe([ANYONE],CLERIC_CURE_MEDIUM_WOUNDS)
        SpellCastOnMe([ANYONE],CLERIC_CURE_SERIOUS_WOUNDS)
THEN
	RESPONSE #100
		SetGlobal("HealedMe","ACIL1W",1)
		StartDialogueNoSet([PC])
END

/*
IF
	Global("Killed_Deer","ACIL1W",1)
THEN
	RESPONSE #100
		SetGlobal("Killed_Deer","ACIL1W",2)
		Kill(Myself)
END
*/

