IF
	GlobalGT("AC#BreskDrowPriestess","GLOBAL",4)
THEN
	RESPONSE #100
		EscapeArea()
END

IF
	!Allegiance(Myself,ENEMY)
	Global("AC#BreskDrowPriestess","GLOBAL",4)
THEN
	RESPONSE #100
		Enemy()
END

IF
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN55",Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",6)
		UseItem("POTN55",Myself)
END

IF
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN52",Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",6)
		UseItem("POTN52",Myself)
END

IF
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN08",Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",6)
		UseItem("POTN08",Myself)
END

IF
	HitBy([ANYONE],CRUSHING)
	Global("GiantStrengthPotion","LOCALS",0)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN05",Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",6)
		SetGlobal("GiantStrengthPotion","LOCALS",1)
		UseItem("POTN05",Myself)
END

IF
	HitBy([ANYONE],CRUSHING)
	Global("GiantStrengthPotion","LOCALS",0)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN07",Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",6)
		SetGlobal("GiantStrengthPotion","LOCALS",1)
		UseItem("POTN07",Myself)
END

IF
	HPPercentLT(Myself,60)
	Global("InvulnerabilityPotion","LOCALS",0)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN11",Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",6)
		SetGlobal("InvulnerabilityPotion","LOCALS",1)
		UseItem("POTN11",Myself)
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	Global("HastePotion","LOCALS",0)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN14",Myself)
THEN
	RESPONSE #100
		SetGlobal("HastePotion","LOCALS",1)
		SetGlobalTimer("SawEnemy","LOCALS",3)
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	Global("HastePotion","LOCALS",1)
	GlobalTimerExpired("SawEnemy","LOCALS")
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN14",Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",6)
		SetGlobal("HastePotion","LOCALS",2)
		UseItem("POTN11",Myself)
END

IF
	See(NearestEnemyOf(Myself))
	!Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		AttackReevaluate(LastAttackerOf(Myself),30)
END





