IF
	!Allegiance(Myself,ENEMY)
	OR(4)
		See([0.0.0.CLERIC_ALL])
		See([0.0.0.BARD_ALL])
		See([0.0.0.DRUID_ALL])
		See([0.0.0.LONG_BOW])
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	OR(4)
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.LONG_BOW]))
THEN
	RESPONSE #100
		Shout(152)
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),15)
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Shout(152)
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),15)
END
