IF
	OnCreation()
THEN
	RESPONSE #100
		StartTimer(77,6)
END

IF
	HPLT(Myself,12)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		StartTimer(77,6)
		ChangeAnimationNoEffect("AC#TROB2")
END

IF
	TimerExpired(77)
THEN
	RESPONSE #100
		StartTimer(77,6)
END

IF
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,50)
	Global("gate","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("gate","LOCALS",1)
		ReallyForceSpellRES("AC#TRB1",NearestEnemyOf(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	Delay(6)
	Global("gate","LOCALS",0)
	Global("Prep","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("gate","LOCALS",1)
		ReallyForceSpellRES("AC#TRB1",ThirdNearestEnemyOf(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Global("Prep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Prep","LOCALS",1)
		SetGlobal("Lightning","LOCALS",1)
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Kugelblitz)
END

IF
	Delay(6)
	See(NearestEnemyOf(Myself))
	Global("Prep","LOCALS",2)
	Global("Lightning","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Lightning","LOCALS",2)
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Kugelblitz)
END

IF
	Delay(3)
	See(NearestEnemyOf(Myself))
	Global("Prep","LOCALS",1)
THEN
	RESPONSE #100
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)  // SPWI302.SPL (Magie bannen)
		SetGlobal("Prep","LOCALS",2)
END

IF
	Global("LichTelTrack","LOCALS",0)
	AttackedBy([GOODCUTOFF],DEFAULT)
	HPPercentLT(Myself,50)
THEN
	RESPONSE #100
		SetGlobal("LichTelTrack","LOCALS",1)
		SetGlobal("TimeToTeleport","LOCALS",0)
		SetGlobalTimer("LichTel","LOCALS",TWO_MINUTES)
		DisplayString(Myself,14117)  // Teleportieren
		ReallyForceSpellPointRES("lichtel",[997.374])  // No such index
	RESPONSE #100
		SetGlobal("LichTelTrack","LOCALS",2)
		SetGlobal("TimeToTeleport","LOCALS",0)
		SetGlobalTimer("LichTel","LOCALS",TWO_MINUTES)
		DisplayString(Myself,14117)  // Teleportieren
		ReallyForceSpellPointRES("lichtel",[1331.293])  // No such index
	RESPONSE #100
		SetGlobal("LichTelTrack","LOCALS",3)
		SetGlobal("TimeToTeleport","LOCALS",0)
		SetGlobalTimer("LichTel","LOCALS",TWO_MINUTES)
		DisplayString(Myself,14117)  // Teleportieren
		ReallyForceSpellPointRES("lichtel",[1475.548])  // No such index
	RESPONSE #100
		SetGlobal("LichTelTrack","LOCALS",4)
		SetGlobal("TimeToTeleport","LOCALS",0)
		SetGlobalTimer("LichTel","LOCALS",TWO_MINUTES)
		DisplayString(Myself,14117)  // Teleportieren
		ReallyForceSpellPointRES("lichtel",[1207.691])  // No such index
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),5)
END

IF
	AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		AttackReevaluate(LastAttackerOf(Myself),5)
END

