IF
	Global("Gith_Spawn","ACIL46",10)
THEN
	RESPONSE #100
                 EscapeArea()
END

IF
	Global("Gith_Spawn","ACIL46",6)
	Dead("AC#DRAS3")
	Dead("AC#GITH9")
	CombatCounter(0)
THEN
	RESPONSE #100
                 SetGlobal("Gith_Spawn","ACIL46",7)
                 Dialogue([PC])
END

IF
	Global("Gith_Spawn","ACIL46",6)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
 	         ChangeEnemyAlly(Myself,GOODBUTBLUE)
		 Attack("AC#DRAS3")
END