IF
	OnCreation()
THEN
	RESPONSE #100
		ApplySpell(Myself,TROLL_SETHP1)
		PlayDead(300)
		ReallyForceSpellRES("AC#URSU2",Myself) // Verwandlung in einen Mur-Zagul
END

IF
	//Allegiance(Myself,NEUTRAL)
	!StateCheck(Myself,STATE_REALLY_DEAD)
	HitBy([PC],SLASHING)
	OR(3)
		HasItemEquipedReal("SW2H10",LastHitter(Myself))  // Carsomyr
		HasItemEquipedReal("NPSW03",LastHitter(Myself))  // Keldorns Sword
		HasItemEquipedReal("SW1H62",LastHitter(Myself))  // Fllar
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		DisplayStringNoNameHead(LastHitter(Myself),999999)  // Das heilige Schwert dringt durch das Fleisch des damönischen Trolls und zerreißt ihn in seine Einzelteile.
		Kill(Myself)
		SetInterrupt(TRUE)
END


