/*
IF
	//Allegiance(Myself,NEUTRAL)
	!StateCheck(Myself,STATE_REALLY_DEAD)
	HitBy([PC],SLASHING)
	OR(3)
		HasItemEquipedReal("SW2H10",LastHitter(Myself))  // Carsomyr
		HasItemEquipedReal("NPSW03",LastHitter(Myself))  // Keldorns Sword
		HasItemEquipedReal("SW1H62",LastHitter(Myself))  // Fllar
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		DisplayStringNoNameHead(LastHitter(Myself),999999)  // Das heilige Schwert dringt durch das Fleisch des damönischen Trolls und zerreißt ihn in seine Einzelteile.
		Kill(Myself)
		SetInterrupt(TRUE)
END
*/

IF
	OnCreation()
THEN
	RESPONSE #100
		StartTimer(77,6)
END

IF
	HPLT(Myself,12)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		StartTimer(77,6)
		ChangeAnimationNoEffect("AC#TRMU2")
END

IF
	TimerExpired(77)
THEN
	RESPONSE #100
		StartTimer(77,6)
END

IF
	//Allegiance(Myself,NEUTRAL)
	!StateCheck(Myself,STATE_REALLY_DEAD)
	HitBy([PC],SLASHING)
	OR(3)
		HasItemEquipedReal("SW2H10",LastHitter(Myself))  // Carsomyr
		HasItemEquipedReal("NPSW03",LastHitter(Myself))  // Keldorns Sword
		HasItemEquipedReal("SW1H62",LastHitter(Myself))  // Fllar
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		DisplayStringNoNameHead(LastHitter(Myself),999999)  // Das heilige Schwert dringt durch das Fleisch des damönischen Trolls und zerreißt ihn in seine Einzelteile.
		Kill(Myself)
		SetInterrupt(TRUE)
END

IF
	Detect([PC])
	Global("AC#URSU","GLOBAL",0)
THEN
	RESPONSE #100
	        SetGlobal("AC#URSU","GLOBAL",1)
		StartDialogueNoSet([PC])
END

IF
	See(NearestEnemyOf(Myself))
	Global("prepspells","LOCALS",0)
THEN
	RESPONSE #100
		ForceSpell(Myself,WIZARD_HASTE) // SPWI305.SPL (Hast)
		ReallyForceSpellRES("AC#MURZ1",Myself) // Protection from Good
		SetGlobal("prepspells","LOCALS",1)
END

IF
	See(NearestEnemyOf(Myself))
	Global("prepspells","LOCALS",1)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
		SetGlobal("prepspells","LOCALS",2)
END

IF
	Global("Behavior","LOCALS",0)
	See(SecondNearestEnemyOf(Myself))
	HPGT(Myself,55)
THEN
	RESPONSE #100
		FaceObject(SecondNearestEnemyOf(Myself))
		ForceSpell(SecondNearestEnemyOf(Myself),WIZARD_BURNING_HANDS) // SPWI103.SPL (Brennende Hände)
                SetGlobal("Behavior","LOCALS",1)
		Wait(1)
END

IF
	//See(NearestEnemyOf(Myself))
	AttackedBy([GOODCUTOFF],DEFAULT)
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	HPPercentLT(Myself,50)
	GlobalLT("invcounter","LOCALS",4)
	Global("invisible","LOCALS",0)
	//!GlobalTimerNotExpired("ThiefHide","LOCALS")
THEN
	RESPONSE #100
		//SetGlobalTimer("ThiefHide","LOCALS",6)
		ForceSpell(Myself,WIZARD_INVISIBILITY) // SPWI206.SPL (Unsichtbarkeit)
		IncrementGlobal("invcounter","LOCALS",1)
		SetGlobal("invisible","LOCALS",1)
		StartTimer(55,60)
		RunAwayFrom(LastAttackerOf(Myself),60)
END

IF
	TimerExpired(55)
	Global("invisible","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("invisible","LOCALS",0)
END

IF
	Global("Behavior","LOCALS",1)
	See([PC])
	HPGT(Myself,15)
THEN
	RESPONSE #100
		FaceObject([PC])
		ForceSpell([PC],WIZARD_BURNING_HANDS) // SPWI103.SPL (Brennende Hände)
		SetGlobal("Behavior","LOCALS",2)
		Wait(1)
END

IF
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),5)
END

IF
	AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		AttackReevaluate(LastAttackerOf(Myself),5)
END
