IF
        Global("AC#Vampire_Killed","ACIL1U",1)
THEN
	RESPONSE #100
		SetGlobal("AC#Vampire_Killed","ACIL1U",0)
		Lock("DOOR01")
		TriggerActivation("Info_Vampire",FALSE)
END

IF
	Die()
THEN
	RESPONSE #100
	ReallyForceSpellDeadRES("AC#VAMP1",Myself) // No such index
END
/*
IF
	HPLT(Myself,10)
THEN
	RESPONSE #100
		ReallyForceSpellDead(Myself,VAMPIRE_BAT_FORM_CHANGE)
END

IF
	TimeGT(5)
	TimeLT(DUSK_END)
	AreaType(OUTDOOR)
THEN
	RESPONSE #100
		ReallyForceSpellDead(Myself,VAMPIRE_BAT_FORM_CHANGE)
END
*/
IF
	See([PC])
	Delay(12)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ForceSpell([PC],VAMPIRE_DOMINATION)
END

