IF
	Global("EnteredArea","ACIL64",0)
THEN
	RESPONSE #100
		SetMusic(NIGHT,%AC#IL56%)
		SetMusic(DAY,%AC#IL56%)		
		TriggerActivation("Tracil63",FALSE)
		SetGlobal("EnteredArea","ACIL64",1)	
END

IF
    GlobalGT("AC#AzerkynDestroyed","GLOBAL",1)
    Global("EnteredArea","ACIL64",1)
THEN
    RESPONSE #100
        SetGlobal("EnteredArea","ACIL64",2)
        ActionOverride("AC#DUN64",Deactivate(Myself))
        TriggerActivation("Tracil62",FALSE)
        TriggerActivation("Tracil63",TRUE)
END

IF
    GlobalGT("AC#Mithbarak_Rescued","GLOBAL",0)
    Global("SwitchBackTravel","ACIL64",0)
THEN
    RESPONSE #100
        SetGlobal("SwitchBackTravel","ACIL64",1)
        TriggerActivation("Tracil62",TRUE)
        TriggerActivation("Tracil63",FALSE)
END

IF
    Global("AC#ACIL64_Open","GLOBAL",2)
    Global("Create_Creatures","ACIL64",0)
THEN
    RESPONSE #100
        CreateCreature("AC#DUN64",[1558.258],S)  // Dunnabar Steinschulter
        CreateCreature("AC#GROM2",[1639.373],NW)  // Gromi Arnschädel
        SetGlobal("Create_Creatures","ACIL64",1)
END

IF
    GlobalGT("AC#AzerkynDestroyed","GLOBAL",1)
    Global("Mith_Dragon","ACIL64",0)
THEN
    RESPONSE #100
        SetGlobal("Mith_Dragon","ACIL64",1)
END

IF
    Global("Mith_Dragon","ACIL64",1)
THEN
    RESPONSE #100
        ClearAllActions()
        StartCutSceneMode()
        FadeToColor([15.0],0)
        Wait(1)
        ActionOverride(Player1,JumpToPoint([1577.333]))
        ActionOverride(Player2,JumpToPoint([1316.597]))
        ActionOverride(Player3,JumpToPoint([1319.593]))
        ActionOverride(Player4,JumpToPoint([1321.600]))
        ActionOverride(Player5,JumpToPoint([1317.590]))
        ActionOverride(Player6,JumpToPoint([1311.592]))
        MoveViewPoint([1577.333],INSTANT)
        CreateCreature("AC#SORNI",[1383.481],NE)  // Sorni Arnschädel
        CreateCreature("AC#ANT64",[1435.515],NE)  // Anthan Diamantklinge
        CreateCreature("AC#ELERN",[1488.550],NE)  // Elern Abgrundlied
        CreateCreature("AC#TORTH",[1506.575],NE)  // Torth Schwarzstahl
        CreateCreature("AC#STURV",[1304.521],NE)  // Sturvis Abgrundlied
        CreateCreature("AC#FENYL",[1403.572],NE)  // Fenyl Arnschädel
        CreateCreature("AC#TURBA",[1462.599],NE)  // Turbaern Ghalmrin
        CreateCreature("AC#VRONI",[1509.627],NE)  // Vronia Eisenbieger
        CreateCreature("AC#BETTA",[1340.452],E)  // Bettargh Abgrundlied
        Wait(1)
        EndCutSceneMode()
        FadeFromColor([30.0],0)
        SetGlobal("Mith_Dragon","ACIL64",2)
        ActionOverride("AC#GROM2",Dialogue(Player1))
END

IF
    Global("Mith_Dragon","ACIL64",3)
THEN
    RESPONSE #100
        ClearAllActions()
        Wait(1)
        ActionOverride("AC#SORNI",EscapeArea())
        ActionOverride("AC#ANT64",EscapeArea())
        ActionOverride("AC#ELERN",EscapeArea())
        ActionOverride("AC#TORTH",EscapeArea())
        ActionOverride("AC#STURV",EscapeArea())
        ActionOverride("AC#FENYL",EscapeArea())
        ActionOverride("AC#TURBA",EscapeArea())
        ActionOverride("AC#VRONI",EscapeArea())
        ActionOverride("AC#BETTA",EscapeArea())
        SetGlobal("Mith_Dragon","ACIL64",4)
        SetGlobal("AC#Torglor","GLOBAL",1)
END

IF
    Global("AC#Mithbarak_Rescued","GLOBAL",20)
    Global("AC#MithbarakazCurse","GLOBAL",0)
    Global("CreateMithBarakDwarf","ACIL64",0)
THEN
    RESPONSE #100
        SetGlobal("CreateMithBarakDwarf","ACIL64",1)
        ActionOverride("AC#MITH1",DestroySelf())
        OpenDoor("Door01")
        CreateCreature("AC#MITH5",[1617.305],SW)  // König Mith Barak
        ActionOverride("AC#MITH5",SetNumTimesTalkedTo(1))
END

IF
    Global("AC#Mithbarak_Rescued","GLOBAL",20)
    Global("AC#MithbarakazCurse","GLOBAL",1)
    Global("CreateMithBarakDwarf","ACIL64",0)
THEN
    RESPONSE #100
        SetGlobal("CreateMithBarakDwarf","ACIL64",1)
        ActionOverride("AC#MITH1",DestroySelf())
        OpenDoor("Door01")
        CreateCreature("AC#MITHD",[1385.566],SW)  // Mithbarakaz
        ActionOverride("AC#MITH5",SetNumTimesTalkedTo(1))
END

IF
    Global("Regency_Council_Thanks","ACIL64",0)
    GlobalGT("AC#IltkazarCelebration","GLOBAL",2)
THEN
    RESPONSE #100
        CreateCreature("AC#SORNB",[477.1130],NE)  // Sorni Arnschädel
        CreateCreature("AC#ANTAB",[514.1145],NE)  // Anthan Diamantklinge
        CreateCreature("AC#ELERB",[611.1172],NE)  // Elern Abgrundlied
        CreateCreature("AC#GROMB",[687.1191],NE)  // Torth Schwarzstahl
        CreateCreature("AC#STURB",[435.1175],NE)  // Sturvis Abgrundlied
        CreateCreature("AC#FENYB",[529.1197],NE)  // Fenyl Arnschädel
        CreateCreature("AC#TURBB",[599.1263],NE)  // Turbaern Ghalmrin
        CreateCreature("AC#VRONB",[436.1231],NE)  // Vronia Eisenbieger
        CreateCreature("AC#BETTB",[496.1274],E)  // Bettargh Abgrundlied
        SetGlobal("Regency_Council_Thanks","ACIL64",1)
END

