IF
	Global("EnteredArea","ACIL21",0)
THEN
	RESPONSE #100
		SetGlobal("EnteredArea","ACIL21",1)
		AmbientActivate("Driftdisc",FALSE)
        AmbientActivate("Ac#turni",FALSE)
        SoundActivate("Driftsound",FALSE)
        Wait(1)
        FadeFromColor([30.0],0)
		SetMusic(NIGHT,%AC#IL21%)
		SetMusic(DAY,%AC#IL21%)		
		AddJournalEntry(@21021,QUEST)
		//EraseJournalEntry(@21002)
END

/*
IF
	Global("SetMusic","ACIL21",0)
	THEN
	RESPONSE #100
	SetMusic(NIGHT,%AC#IL21%)
	SetMusic(DAY,%AC#IL21%)
	SetGlobal("SetMusic","ACIL21",1)
	Continue()
END
*/

IF
	DifficultyLT(HARD)
	Global("SetRest","ACIL21",0)
THEN
	RESPONSE #100
		SetGlobal("SetRest","ACIL21",1)
		SetRestEncounterProbabilityDay(3)
		SetRestEncounterProbabilityNight(3)
END

IF
	InMyArea(Player1)
	Global("MalphasGithCutscene#1","ACIL21",0) 
	GlobalGT("AC#Goodbye_Iltkazar","GLOBAL",9)
THEN
	RESPONSE #100
		FadeToColor([8.0],0)
		SetGlobal("MalphasGithCutscene#1","ACIL21",1)  
		SmallWait(3)
		StartCutSceneMode()
		StartCutScene("AC#GCT1")
END

// after talk to Maldraedior
// creates Elghonn cre
IF
	GlobalGT("AC#Talked_to_Maldraedior","GLOBAL",0)
	Global("ElghonnSpawn","ACIL21",0)
THEN
	RESPONSE #100
		SetGlobal("ElghonnSpawn","ACIL21",1)
		CreateCreature("AC#ELGHO",[1963.970],6)
END

// after talk to Maldraedior
// creates Black pudding cre
IF
	GlobalGT("AC#Talked_to_Maldraedior","GLOBAL",0)
	Global("PuddingSpawn","ACIL21",0)
THEN
	RESPONSE #100
		SetGlobal("PuddingSpawn","ACIL21",1)
		CreateCreature("AC#BLPU1",[2355.508],8)
END

// after talk to Maldraedior
// creates various other spawned creatures
IF
	GlobalGT("AC#Talked_to_Maldraedior","GLOBAL",0)
	Global("EnemySpawn","ACIL21",0)
THEN
	RESPONSE #100
		SetGlobal("EnemySpawn","ACIL21",1)
		CreateCreature("AC#UMHUL",[926.1441],4)
		CreateCreature("ICSALCOL",[3004.1411],7)
		CreateCreature("ICSALCOL",[2987.1580],9)
END


