IF
	Global("DisableAnimations","ACIL36",0)
THEN
	RESPONSE #100
	SetGlobal("DisableAnimations","ACIL36",1)
    AmbientActivate("Stone_broken",FALSE)
	EraseJournalEntry(@62047)
	AddJournalEntry(@62048,QUEST_DONE)
END

IF
	Global("GolemDoor","ACIL36",1)
        OpenState("DOOR01",FALSE)
THEN
	RESPONSE #100
                Wait(1)
                OpenDoor("DOOR01")
                AmbientActivate("Stone_closed",FALSE)
                PlaySound("EFF_P92")
                AmbientActivate("Stone_broken",TRUE)
		SetGlobal("GolemDoor","ACIL36",2)
END

