// old scripts, now triggered via dialogues
/*
IF
	Global("AC#ACIL23CutScene1","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("AC#ACIL23CutScene1","GLOBAL",4)
		ClearAllActions()
		StartCutSceneMode()
		StartCutScene("AC#23CT2")
END

IF
	Global("AC#ACIL23CutScene1","GLOBAL",5)
THEN
	RESPONSE #100
		SetGlobal("AC#ACIL23CutScene1","GLOBAL",6)
		ClearAllActions()
		StartCutSceneMode()
		StartCutScene("AC#23CT3")
END
*/
