IF
	Global("EnteredArea","ACIL21",0)
THEN
	RESPONSE #100
		SetGlobal("EnteredArea","ACIL21",1)
		AmbientActivate("Driftdisc",FALSE)
        AmbientActivate("Ac#turni",FALSE)
        SoundActivate("Driftsound",FALSE)
        Wait(1)
        FadeFromColor([30.0],0)
		SetMusic(NIGHT,%AC#IL21%)
		SetMusic(DAY,%AC#IL21%)		
		SpawnPtDeactivate("Slime")
		SpawnPtDeactivate("Spawn04")
		SpawnPtDeactivate("Spawn05")
		AddJournalEntry(@21021,QUEST)
		//EraseJournalEntry(@21002)
END

/*
IF
	Global("SetMusic","ACIL21",0)
	THEN
	RESPONSE #100
	SetMusic(NIGHT,%AC#IL21%)
	SetMusic(DAY,%AC#IL21%)
	SetGlobal("SetMusic","ACIL21",1)
	Continue()
END
*/

IF
	DifficultyLT(HARD)
	Global("SetRest","ACIL21",0)
THEN
	RESPONSE #100
		SetGlobal("SetRest","ACIL21",1)
		SetRestEncounterProbabilityDay(3)
		SetRestEncounterProbabilityNight(3)
END

IF
	InMyArea(Player1)
	Global("MalphasGithCutscene#1","ACIL21",0) 
	GlobalGT("AC#Goodbye_Iltkazar","GLOBAL",9)
THEN
	RESPONSE #100
		FadeToColor([8.0],0)
		SetGlobal("MalphasGithCutscene#1","ACIL21",1)  
		SmallWait(3)
		StartCutSceneMode()
		StartCutScene("AC#GCT1")
END

IF
    PartyHasItem("AC#DRFT2")  // Schwebescheibe
    Global("ChangeSpawnPoints","ACIL21",0)
THEN
    RESPONSE #100
		SpawnPtActivate("Slime")
		SpawnPtActivate("Spawn04")
		SpawnPtActivate("Spawn05")
        SetGlobal("ChangeSpawnPoints","ACIL21",1)
END

/*
IF
    PartyHasItem("AC#DRFT2")  // Schwebescheibe
    Global("ElghonnSpawn","ACIL21",0)
THEN
    RESPONSE #100
        SetGlobal("ElghonnSpawn","ACIL21",1)
        CreateCreature("AC#ELGHO",[1963.970],NW)  // Elghonn
END
*/

IF
    PartyHasItem("AC#DRFT2")  // Schwebescheibe
    Global("PuddingSpawn","ACIL21",0)
THEN
    RESPONSE #100
        SetGlobal("PuddingSpawn","ACIL21",1)
        CreateCreature("AC#BLPU1",[2355.508],N)  // Schwarzer Pudding
END

IF
    PartyHasItem("AC#DRFT2")  // Schwebescheibe
    Global("EnemySpawn","ACIL21",0)
THEN
    RESPONSE #100
        SetGlobal("EnemySpawn","ACIL21",1)
        CreateCreature("AC#UMHUL",[926.1441],W)  // Erdkoloss
        //CreateCreature("ICSALCOL",[3004.1411],NNW)  // Eissalamander
        //CreateCreature("ICSALCOL",[2987.1580],NNE)  // Eissalamander
END




