IF
	Global("Gogondy_Brazier","ACIL2K",0)
THEN
	RESPONSE #100
		SetGlobal("Gogondy_Brazier","ACIL2K",1)
		AmbientActivate("Red_smoke_01",FALSE)
                AmbientActivate("Red_smoke_02",FALSE)
                OpenDoor("Door01")
                OpenDoor("Door02")
END

IF
	Global("Brazier01","ACIL2K",2)
THEN
	RESPONSE #100
		SetGlobal("Brazier01","ACIL2K",3)
		AmbientActivate("Green_smoke_01",FALSE)
                //AmbientActivate("Green_smoke_02",FALSE)
                AmbientActivate("Red_smoke_01",TRUE)
                //AmbientActivate("Red_smoke_02",TRUE)
                CloseDoor("Door01")
                //CloseDoor("Door02")
END

IF
	Global("Brazier02","ACIL2K",2)
THEN
	RESPONSE #100
		SetGlobal("Brazier02","ACIL2K",3)
		//AmbientActivate("Green_smoke_01",FALSE)
                AmbientActivate("Green_smoke_02",FALSE)
                //AmbientActivate("Red_smoke_01",TRUE)
                AmbientActivate("Red_smoke_02",TRUE)
                //CloseDoor("Door01")
                CloseDoor("Door02")
END

IF
	Global("Brazier01","ACIL2K",3)
	Global("Brazier02","ACIL2K",3)
	Global("AC#kuotoa_madness","GLOBAL",0)
THEN
	RESPONSE #100
	        TakePartyItem("AC#GOGON")
	        EraseJournalEntry(@56200)
	        AddJournalEntry(@56201,QUEST_DONE)
			AddExperienceParty(10000)
		SetGlobal("AC#kuotoa_madness","GLOBAL",1)
END

IF
       PartyHasItem("AC#IL#01")
       Global("Runestone","ACIL2K",0)
THEN
	RESPONSE #100
		SetGlobal("Runestone","ACIL2K",1)
		EraseJournalEntry(@56102)
		AddJournalEntry(@56111,QUEST)
END