IF
	Global("EnteredArea","ACIL21",0)
THEN
	RESPONSE #100
		SetGlobal("EnteredArea","ACIL21",1)
		AmbientActivate("Driftdisc",FALSE)
        AmbientActivate("Ac#turni",FALSE)
        SoundActivate("Driftsound",FALSE)
        Wait(1)
        FadeFromColor([30.0],0)
		SetMusic(NIGHT,%AC#IL21%)
		SetMusic(DAY,%AC#IL21%)		
		SpawnPtDeactivate("Slime")
		SpawnPtDeactivate("Spawn04")
		SpawnPtDeactivate("Spawn05")
		AddJournalEntry(@21021,QUEST)
		//EraseJournalEntry(@21002)
END

IF
    Global("AC#_IL_Area_21","GLOBAL",0)
    GlobalGT("AC#IL_Entered_ACIL20","GLOBAL",0)
	InMyArea(Player1)
THEN
    RESPONSE #100
        SetGlobal("AC#_IL_Area_21","GLOBAL",1)
        DisplayString(Myself,@7102)
        AdvanceTime(FOUR_HOURS)
END

IF
	DifficultyLT(HARD)
	Global("SetRest","ACIL21",0)
THEN
	RESPONSE #100
		SetGlobal("SetRest","ACIL21",1)
		SetRestEncounterProbabilityDay(3)
		SetRestEncounterProbabilityNight(3)
END

IF
    PartyHasItem("AC#DRFT2")  // Schwebescheibe
    Global("ChangeSpawnPoints","ACIL21",0)
THEN
    RESPONSE #100
		SpawnPtActivate("Slime")
		SpawnPtActivate("Spawn04")
		SpawnPtActivate("Spawn05")
        SetGlobal("ChangeSpawnPoints","ACIL21",1)
END

/*
IF
    PartyHasItem("AC#DRFT2")  // Schwebescheibe
    Global("ElghonnSpawn","ACIL21",0)
THEN
    RESPONSE #100
        SetGlobal("ElghonnSpawn","ACIL21",1)
        CreateCreature("AC#ELGHO",[1963.970],NW)  // Elghonn
END
*/

IF
    PartyHasItem("AC#DRFT2")  // Schwebescheibe
    Global("PuddingSpawn","ACIL21",0)
THEN
    RESPONSE #100
        SetGlobal("PuddingSpawn","ACIL21",1)
        CreateCreature("AC#BLPU1",[2355.508],N)  // Schwarzer Pudding
END

IF
    PartyHasItem("AC#DRFT2")  // Schwebescheibe
    Global("EnemySpawn","ACIL21",0)
THEN
    RESPONSE #100
        SetGlobal("EnemySpawn","ACIL21",1)
        CreateCreature("AC#UMHUL",[926.1441],W)  // Erdkoloss
        //CreateCreature("ICSALCOL",[3004.1411],NNW)  // Eissalamander
        //CreateCreature("ICSALCOL",[2987.1580],NNE)  // Eissalamander
END




