IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        MultiPlayerSync()
        Explore()
        SmallWait(5)
        ActionOverride("AC#DREA8",MoveToPoint([609.811]))
        ActionOverride("AC#DREA9",MoveToPoint([586.891]))
        MoveViewPoint([609.811],5)
        Wait(5)
        ActionOverride("AC#DREA8",Face(SEE))
        ActionOverride("AC#DREA8",StartDialogueNoSet(Player1))
END

