IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		ActionOverride("AC#DREA8",MoveToPoint([372.607]))
		ActionOverride("AC#DREA9",MoveToPoint([2080.1600]))
		FadeToColor([50.0],0)
		Wait(3)
		RestorePartyLocations()
		MultiPlayerSync()
		FadeFromColor([30.0],0)
		EndCutSceneMode()
		StartMovie("AC#23MVE")
		RestParty()
		//ActionOverride(Player1,StartDialog("Player1",Myself))
		SetGlobal("AC#ACIL23DreamReflection","GLOBAL",1)
END

/*
IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		FadeToColor([30.0],0)
		Wait(1)
		Wait(1)
		LeaveAreaLUAPanic("ACILD1","",[0.0],0)
		LeaveAreaLUA("ACILD1","",[0.0],8)
		ActionOverride(Player2,LeaveAreaLUA("ACILD1","",[0.0],2))
		ActionOverride(Player3,LeaveAreaLUA("ACILD1","",[0.0],14))
		ActionOverride(Player4,LeaveAreaLUA("ACILD1","",[0.0],0))
		ActionOverride(Player5,LeaveAreaLUA("ACILD1","",[0.0],4))
		ActionOverride(Player6,LeaveAreaLUA("ACILD1","",[0.0],2))
		MultiPlayerSync()
		MoveViewPoint([2080.1600],INSTANT)
		ApplySpell(Player2,SURE_SLEEP) // SPIN892.SPL (Schlaf)
		ApplySpell(Player3,SURE_SLEEP) // SPIN892.SPL (Schlaf)
		ApplySpell(Player4,SURE_SLEEP) // SPIN892.SPL (Schlaf)
		ApplySpell(Player5,SURE_SLEEP) // SPIN892.SPL (Schlaf)
		ApplySpell(Player6,SURE_SLEEP) // SPIN892.SPL (Schlaf)
		Explore()
		SmallWait(5)
		FadeFromColor([40.0],0)
		ActionOverride("AC#DREA8",MoveToPoint([1066.1059]))
		ActionOverride("AC#DREA9",MoveToPoint([1003.1133]))
		//Wait(5)
		MoveViewPoint([1066.1059],5)
		Wait(10)
		//ActionOverride("AC#DREA1",Face(2))
		//ActionOverride("AC#DREA1",SmallWait(5))
		//MoveViewObject("AC#DREA1",5)
		Wait(3)
		//ActionOverride("AC#DREA8",StartDialogueNoSet(Player1))
		FadeToColor([50.0],0)
		RestorePartyLocations()
		MultiPlayerSync()
		FadeFromColor([30.0],0)
		EndCutSceneMode()
		RestParty()
END
*/

